---
title: "ParseMultiSim"
output: html_document
date: "2023-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo =FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
library(gridExtra)
library(viridis)

expit <- function(x){
  return(exp(x) / (1+exp(x)))
}

logit <- function(x){
  return(log(x/(1-x)))
}

Param2TranHelper <- function(p12,p21){
  tran <- matrix(0,2,2)
  tran[1,2] <- expit(p12)
  tran[1,1] <- 1- tran[1,2]
  tran[2,1] <- expit(p21)
  tran[2,2] <- 1 - tran[2,1]
  return(tran)
}
  
Params2Tran <- function(params_tran,time,index){
  
  harmonic_ind <- ((index*2)-1)+6
  #####by row is different here
  param_matrix <- matrix(params_tran,ncol=18,nrow=2, byrow = F)
  if (index == 1){
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,7]*cos(2*pi*time/96)+param_matrix[1,8]*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,7]*cos(2*pi*time/96)+param_matrix[2,8]*sin(2*pi*time/96))
  } else {
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,index]+
                               (param_matrix[1,7]+param_matrix[1,harmonic_ind])*cos(2*pi*time/96)+
                               (param_matrix[1,8]+param_matrix[1,harmonic_ind+1])*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,index]+
                               (param_matrix[2,7]+param_matrix[2,harmonic_ind])*cos(2*pi*time/96)+
                               (param_matrix[2,8]+param_matrix[2,harmonic_ind+1])*sin(2*pi*time/96))
  }
  return(tran)
}


tran_covar_num <- 6

Tran2DF <- function(params_tran){
  race_list <- c("0","1","2","3","4","5") 
  
  
  tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=1)
  tran_df <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[1])
  
  for (i in 2:tran_covar_num){
    tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=i)
    tran_df_working <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[i])
    
    tran_df <- rbind(tran_df,tran_df_working)
  }
  
  return(tran_df)
}
  
setwd("MeanRemovedNWAge/")
file_list <- list.files()
file_length <- length(file_list)

load(file_list[1])
n <- dim(params_to_save[[3]])[2]
bigT <- dim(params_to_save[[3]])[1]

init_est_array <- matrix(0,2,file_length)

tran_est_array <- array(0,dim = c(2,18,file_length))

act_est_array <- list(matrix(0,2,2))

binom_est_array <- matrix(0,2,file_length)

pi_est_array <- list(numeric(2))

re_prob_mat <- matrix(0,n,file_length)

act_decode_list <- list(matrix(0,bigT,n))

AIC_vec <- numeric(file_length)
BIC_vec <- numeric(file_length)

for (file_ind in 1:file_length){
  load(file_list[file_ind])

  init_est_array[,file_ind] <- params_to_save[[1]][[1]]

  # tran_est_array[,,file_ind] <- params_to_save[[1]][[2]]
  tran_est_array[,,file_ind] <- matrix(params_to_save[[1]][[2]],2,18,byrow = T) 

  
  act_est_array[length(act_est_array)+1] <- list(params_to_save[[1]][[3]])

  binom_est_array[,file_ind] <- params_to_save[[1]][[4]]
  
  pi_est_array[length(pi_est_array)+1] <- list(params_to_save[[1]][[5]])
  
  re_prob_mat[,file_ind] <- apply(params_to_save[[1]][[6]],1,which.max)
  
  
  act_decode_list[length(act_decode_list)+1] <- list(params_to_save[[3]])
  
  AIC_vec[file_ind] <- params_to_save[[6]][[1]]
  BIC_vec[file_ind] <- params_to_save[[6]][[2]]

}

act_est_array <- act_est_array[-1]
pi_est_array <- pi_est_array[-1]
act_decode_list <- act_decode_list[-1]

```

```{r}
load("Wavedata_G.rda")
load("Wavedata_H.rda")
  
sim_num <- as.numeric(Sys.getenv('SLURM_ARRAY_TASK_ID'))


id_G <- wave_data_G[[4]]
id_H <- wave_data_H[[4]]
id <- rbind(id_G,id_H)
id2 <- rbind(wave_data_G[[3]],wave_data_H[[3]])

log_sweights_vec_G <- log(id_G[,3])
log_sweights_vec_H <- log(id_H[,3])

log_sweights_vec <- c(log_sweights_vec_G/2,log_sweights_vec_H/2)

id <- id %>% mutate(age_disc = case_when(age <= 10 ~ 1,
                                   age <=20 & age > 10 ~ 2,
                                   age <=35 & age > 20 ~ 3,
                                   age <=50 & age > 35 ~ 4,
                                   age <=65 & age > 50 ~ 5,
                                   age > 65 ~ 6))

id <- id %>% mutate(pov_disc = floor(poverty)+1)

id <- id %>% mutate(bmi_disc = case_when(BMI <= 18.5 ~ 1,
                                   BMI <=25 & BMI > 18.5 ~ 2,
                                   BMI <=30 & BMI > 25 ~ 3,
                                   BMI <=35 & BMI > 30 ~ 4,
                                   BMI <=40 & BMI > 35 ~ 5,
                                   BMI > 40 ~ 6))

#CHANGE RACE AND POV
pov_mat_tran <- matrix(0,ncol = 6, nrow = length(id$pov_disc))
pov_mat_tran[,1] <- 1
for (i in 1:length(id$pov_disc)){
  pov_mat_tran[i,id$pov_disc[i]] <- 1
} 
tran_pov_vec <- apply(pov_mat_tran,1,ChooseTran)

age_mat_tran <- matrix(0,ncol = 6, nrow = length(id$age_disc))
age_mat_tran[,1] <- 1
for (i in 1:length(id$age_disc)){
  age_mat_tran[i,id$age_disc[i]] <- 1
} 
tran_age_vec <- apply(age_mat_tran,1,ChooseTran)

epsilon <- 1e-3
act_G <- log(wave_data_G[[1]] + epsilon)
act_H <- log(wave_data_H[[1]] + epsilon)

#remove SEQN identifier
act_G <- t(act_G)[2:dim(act_G)[2],]
act_H <- t(act_H)[2:dim(act_H)[2],]

act <- cbind(act_G,act_H)
```


```{r}
 race_list <- c("Mexican American","Other Hispanic","NH White",
               "NH Black","NH Asian","Other Race - Including Multi-Racial")

 race_list <- c("0-1","1-2","2-3",
               "3-4","4-5","5+")
 
race_list <- c("3-10","11-20","21-35","36-50","50-65","65+")

race_list <- factor(race_list, levels = race_list)

Params2DFHelper <- function(tran_est_array,re_num){
  
  tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = tran_est_array[,,re_num],index=1)
  tran_df <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[1],
                        re_num = re_num)
  
  for (i in 2:6){
    tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = tran_est_array[,,re_num],index=i)
    tran_df_working <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[i],
                        re_num = re_num)
    
    tran_df <- rbind(tran_df,tran_df_working)
  }
  return(tran_df)
}

Params2DF <- function(tran_est_array){
  
  tran_df <- Params2DFHelper(tran_est_array,1)
  
  for (re_ind in 2:dim(tran_est_array)[3]){
    tran_df_working <- Params2DFHelper(tran_est_array,re_ind)
    
    tran_df <- rbind(tran_df,tran_df_working)
  }
  return(tran_df)
}
```

```{r,fig.width=7.5}

nre.labs <- c("Ind HMM","Shared HMM",paste(c(2:8), "Support Points"))
names(nre.labs) <- c(1:9)

tran_df_total <- Params2DF(tran_est_array)
# tran_df_total<- Params2DFHelper(tran_est_array,1)

ggplot(tran_df_total %>% filter(type == "Sleep"), aes(x = time,y = prob, color = race)) + 
  geom_line() + 
  labs(title = "Probability of Falling Asleep by Hour", x = "Hour", 
       y = "Probability of Falling Asleep",color = "Age") +
  facet_wrap(vars(re_num),labeller = labeller(re_num = nre.labs))+
  scale_color_viridis(discrete=TRUE,end=.9) 

ggplot(tran_df_total %>% filter(type == "Wake"), aes(x = time,y = prob, color = race)) + 
  geom_line() + 
  labs(title = "Probability of Waking by Hour", x = "Hour", 
       y = "Probability of Falling Asleep",color = "Age") +
  facet_wrap(vars(re_num),labeller = labeller(re_num = nre.labs))+
  scale_color_viridis(discrete=TRUE,end=.9) 
```

```{r,fig.width=7.5}

mixing_df <- data.frame()
for (re_num in 1:length(pi_est_array)){
  mixing_df_working <- data.frame(mix = pi_est_array[[re_num]],
                          mean = act_est_array[[re_num]][1,1,],
                          re_num = re_num)
  
  mixing_df <- rbind(mixing_df,mixing_df_working)
}

  

ggplot(mixing_df, aes(y=mix, x=mean)) + 
  geom_point() +
  facet_wrap(vars(re_num),labeller = labeller(re_num = nre.labs))+
  labs(x = "Mixing Proportion",
       y = "Wake Activity Mean",
       title = "Wake Activity Mean by Mixing Proportion by # of Support Points")

```

```{r}
  

ScatterByRE <- function(est_array,ind1,ind2){
  scatter_df <- data.frame()
  
  
  
  for (re_num in 1:length(est_array)){
    
    if (is.integer(dim(est_array[[1]]))){
      scatter_df_working <- data.frame(est = mean(est_array[[re_num]][ind1,ind2,]),
                              re_num = re_num-1)
    } else {
      
      scatter_df_working <- data.frame(est = est_array[[re_num]],
                              re_num = re_num-1)
      
    }
      
    
    scatter_df <- rbind(scatter_df,scatter_df_working)
  }
  
  scatter_df$re_num <- as.factor(scatter_df$re_num)
  
  return(scatter_df)
  
}
  
PlotScatter <- function(est_array,ind1,ind2,title){
  scatter_df <- ScatterByRE(est_array,ind1,ind2)
  ggplot(scatter_df, aes(x=re_num, y=est)) + 
    geom_point() + 
    labs(x = "Number of Support Points",
         y = "Estimate",
         title = title)
}

PlotScatter(binom_est_array,2,1,"Prob of Below LoD by # of Support Points")
PlotScatter(act_est_array,1,2,"Wake Activity SE by # of Support Points")
PlotScatter(act_est_array,2,1,"Sleep Activity Mean by # of Support Points")
PlotScatter(act_est_array,2,2,"Sleep Activity SE by # of Support Points")
  
```

```{r}

act_decode_array <- simplify2array(act_decode_list)

# test2 <- apply(act_decode_array,c(1,2),var)
# 
# inds <- which(test2 == max(test2,na.rm = T), arr.ind = TRUE)
# tail(sort(table(inds[,2])),20)

re_ind <- 6

init <- init_est_array[,re_ind]
params_tran <- tran_est_array[,,re_ind]
emit_act <- act_est_array[[re_ind]]
act_light_binom <- binom_est_array[,re_ind]
pi_l <- pi_est_array[[re_ind]]

tran_list <- lapply(c(1:dim(covar_mat_tran)[2]),TranByTimeVec, params_tran = params_tran, time_vec = c(1:obs_per_day))
tran_ind_vec <- apply(covar_mat_tran,1,ChooseTran)

readCpp("Scripting/cFunctions.cpp")
readCpp("../Scripting/cFunctions.cpp")

alpha <- ForwardC(act,init,tran_list,emit_act,tran_ind_vec,lepsilon,act_light_binom, log_sweights_vec)
re_prob <- CalcProbRE(alpha,pi_l)

sum(apply(re_prob,1, function(x) any(x > .5)))/dim(re_prob)[1]
sum(apply(re_prob,1, function(x) any(x > .9)))/dim(re_prob)[1]
sum(apply(re_prob,1, function(x) any(x > .99)))/dim(re_prob)[1]





class1 <- which(re_prob[,1] == max(re_prob[,1] ,na.rm = T), arr.ind = TRUE)
class2 <- which(re_prob[,2] == max(re_prob[,2] ,na.rm = T), arr.ind = TRUE)
class3 <- which(re_prob[,3] == max(re_prob[,3] ,na.rm = T), arr.ind = TRUE)
class6 <- which(re_prob[,6] == max(re_prob[,1] ,na.rm = T), arr.ind = TRUE)
```

```{r,fig.height=4,fig.width=10}
# # 
# ind <- class1[4]
# 
# # ind <- class1[6]
# # ind <- class1[10]
# # ind <- class1[24]
# # ind <- class1[25]
# # ind <- class1[42]
# # ind <- class1[48]
# # ind <- class1[49]
# 
# ind <- class2[2]
# 
# # # ind <- class3[1]
# ind <- class3[2]
# # # ind <- class3[8]
# 
# # # ind <- class6[5]
# ind <- class6[7]
# # # ind <- class6[9]

###NEED TO FIX THIS WITH WITH ADDED MODELS

model_vec <- c(0,1,2,3,4,5,6,7,8)
# model_vec <- c(1)

DecodingPlots <- function(ind){
  bigT <- dim(act_decode_array)[1]
  decoded_df <- data.frame(decode = as.vector(act_decode_array[,ind,]),
                           supportpoints = rep(model_vec,each = bigT),
                           lwd = rep(seq(.5,.25,length = length(model_vec)),each = bigT),
                           act = rep(act[,ind],length(model_vec)),
                           time =rep(c(seq(as.POSIXct("2024-01-01"), as.POSIXct("2024-01-10"), by=60*15)[1:bigT]),length(model_vec)))
  
  decoded_df$supportpoints <- as.factor(decoded_df$supportpoints)
  decoded_df$lwd <- as.factor(decoded_df$lwd)
  
  
  #For full data
  decoded_df0 <- decoded_df[1:864,]
  decoded_df1 <- decoded_df[865:1728,]
  decoded_df6 <- decoded_df[6049:6912,]
  time_ticks <- 28
  
  # #For weekend data 
  # decoded_df0 <- decoded_df[1:288,]
  # decoded_df1 <- decoded_df[289:576,]
  # decoded_df6 <- decoded_df[2305:2592,]
  # time_ticks <- 19
  
  # p <- ggplot(decoded_df, aes(x=time, y=decode), size =lwd) +
  #   geom_line(aes(color = supportpoints,linetype = supportpoints)) +
  #   scale_x_datetime(breaks= seq(min(decoded_df$time), max(decoded_df$time)+15*60, length=28), 
  #                    date_labels="%H:%M")+
  #   theme_bw() +
  #   theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + 
  #   scale_y_continuous(breaks=c(0,1), label = c("Wake","Sleep")) +
  #   scale_color_viridis(discrete=TRUE,end=.95) + 
  #   labs(x = "Time",
  #        y="",
  #        title = "Viterbi Decoding by # of Support Points",
  #        linetype = "Support Points",
  #        color = "Support Points") 
  
  g <- ggplot(decoded_df, aes(x=time, y=act)) +
    geom_point() +
    scale_x_datetime(breaks= seq(min(decoded_df$time), max(decoded_df$time)+15*60, length=time_ticks), 
                     date_labels="%H:%M")+
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + 
    labs(x = "Time",
         y = "Acitivity (MIMS)",
         title = "Activity by Time")
  
  p0 <- ggplot(decoded_df0, aes(x=time, y=decode)) +
    geom_path(color = viridis(7)[1]) +
    scale_x_datetime(breaks= seq(min(decoded_df$time), max(decoded_df$time)+15*60, length=time_ticks), 
                     date_labels="%H:%M")+
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = .5, vjust = 0.5))+
    theme(legend.position = "none") + 
    scale_y_continuous(breaks=c(0,1), label = c("Wake","Sleep"))+
    labs(x = "Time",
         y="",
         title = "Individual HMM",
         linetype = "Support Points",
         color = "Support Points") + 
    theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
  
  p1 <- ggplot(decoded_df1, aes(x=time, y=decode)) +
    geom_path(color = viridis(7)[1]) +
    scale_x_datetime(breaks= seq(min(decoded_df$time), max(decoded_df$time)+15*60, length=time_ticks), 
                     date_labels="%H:%M")+
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = .5, vjust = 0.5))+
    theme(legend.position = "none") + 
    scale_y_continuous(breaks=c(0,1), label = c("Wake","Sleep"))+
    labs(x = "Time",
         y="",
         title = "Shared HMM",
         linetype = "Support Points",
         color = "Support Points") + 
    theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
    
  
  p6 <- ggplot(decoded_df6, aes(x=time, y=decode)) +
    geom_path(color = viridis(7)[1]) +
    scale_x_datetime(breaks= seq(min(decoded_df$time), max(decoded_df$time)+15*60, length=time_ticks), 
                     date_labels="%H:%M")+
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = .5, vjust = 0.5))+
    theme(legend.position = "none") + 
    scale_y_continuous(breaks=c(0,1), label = c("Wake","Sleep"))+
    labs(x = "Time",
         y="",
         title = "7 Support Points",
         linetype = "Support Points",
         color = "Support Points")+ 
    theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
  
  return(plot_grid(p1,p0,p6,g, label_size = 10,ncol=1, align = "hv",axis = "tblr",hjust = -2,vjust = 4))
}

```

```{r,fig.height=7.5}
#Cluster 1
#Small diff btwn sleep and wake activity
DecodingPlots(170)
  

#Cluster 2
#Smallish diff btwn sleep and wake activity
DecodingPlots(7)

#Cluster 3
#Medium diff btwn sleep and wake activity
#Heavy sleeper
DecodingPlots(1183)


# #Cluster 6
# #Large diff btwn sleep and wake activity
# DecodingPlots(135)

# DecodingPlots(11)



DecodingPlots(100)



DecodingPlots(2433)


DecodingPlots(132)


DecodingPlots(9)

DecodingPlots(246)
DecodingPlots(397)


```


```{r}
n <- dim(act)[2]

full_data_ind <- which(colSums(!is.na(act)) > 96*6)
# full_data_ind <- which(colSums(!is.na(act)) > 100)

tran_pov_vec2 <- tran_pov_vec[full_data_ind]
tran_age_vec2 <- tran_age_vec[full_data_ind]

ReturnLongestBlockIndex <- function(vit_ind_day,forw_look){
  if (sum(vit_ind_day) == 0){return(0)}
  
  if (sum(vit_ind_day[1:(96-forw_look)])==0){
    return(c(which.max(vit_ind_day),96))
  }
  
  forw_look <- forw_look - 1
  rs <- numeric((length(vit_ind_day)-forw_look))
  for (i in 1:(length(vit_ind_day)-forw_look)){
    if (i > 1){
      rs[i] <- sum(vit_ind_day[i:(i+forw_look)])*max(rs[i-1]>0,vit_ind_day[i])
    } else {
      rs[i] <- sum(vit_ind_day[i:(i+forw_look)])*vit_ind_day[i]
    }
  }
  
  rs <- rs > 0
  runs <- rle(rs)
  lengths <- runs$lengths
  
  end = cumsum(lengths)
  start = c(1, lag(end)[-1] + 1)
  
  is_max <- which(lengths == max(lengths[runs$values]) & runs$values)
  return(c(start[is_max],end[is_max]))
}

  

final_df <- data.frame()

#NEED TO DEAL WITH MISSING DATA


# vit_ind <- act_decode_array[c(49:816),ind,model]
for (model_ind in c(1,9)){
  sleep_block_vec <- c()
  sleep_eff_vec <- c()
  sleep_onset_vec <- c()
  sleep_total_vec <- c()
  
  for (ind in full_data_ind){
    
    vit_ind <- act_decode_array[,ind,model_ind]
    len <- length(vit_ind)
  
    day_len <- (dim(act_decode_array)[1] %/% 96) - 1
    sleep_block_ind_vec <- c()
    sleep_eff_ind_vec <- c()
    sleep_onset_ind_vec <- c()
    sleep_total_ind_vec <- c()
    
    for(day in 1:day_len){
      start_ind <- 49 + (96*(day-1))
      stop_ind <- 48 + (96*day)
      vit_ind_day <- vit_ind[start_ind:stop_ind]
      
      
      block_indices <- ReturnLongestBlockIndex(vit_ind_day,8)
      
      if (length(block_indices)==1){
        sleep_block <- 0
        sleep_eff <- 0
        sleep_onset <- 0
      } else {
        block_start <- block_indices[1]
        block_end <- block_indices[2]
        
        sleep_block <- block_end - block_start + 1
        sleep_eff <- sum(vit_ind_day[block_start:block_end]==1)/sleep_block
        sleep_onset <- block_start + 48
        sleep_total <- sum(vit_ind_day == 1)
      }
      
        
      
      
      
      
      if (sum(is.na(act[start_ind:stop_ind,ind]))>32){
        sleep_block <- NA
        sleep_eff <- NA
        sleep_onset <- NA
        sleep_total <- NA
      }
      
      sleep_block_ind_vec <- c(sleep_block_ind_vec,sleep_block)
      sleep_eff_ind_vec <- c(sleep_eff_ind_vec,sleep_eff)
      sleep_onset_ind_vec <- c(sleep_onset_ind_vec, sleep_onset)
      sleep_total_ind_vec <- c(sleep_total_ind_vec, sleep_total)
    } 
    
    sleep_block_vec <- c(sleep_block_vec,median(sleep_block_ind_vec,na.rm = T))
    sleep_eff_vec <- c(sleep_eff_vec,median(sleep_eff_ind_vec,na.rm = T))
    sleep_onset_vec <- c(sleep_onset_vec,median(sleep_onset_ind_vec,na.rm = T))
    sleep_total_vec <- c(sleep_total_vec,sum(sleep_total_ind_vec)/(day_len+1))
  }
  
  
  working_df <- data.frame(block = sleep_block_vec,
                         eff = sleep_eff_vec,
                         modelnum = model_ind,
                         onset = sleep_onset_vec,
                         totalSleep = sleep_total_vec,
                         pov = tran_pov_vec2,
                         pov_cont = round(id$poverty[full_data_ind],1),
                         age = tran_age_vec2,
                         age_cont = id$age[full_data_ind],
                         race = id$race[full_data_ind],
                         bmi_cont = round(id$BMI[full_data_ind],0),
                         bmi_disc = id$bmi_disc[full_data_ind],
                         gender = id2$gender[full_data_ind],
                         houseFS = id2$houseFS[full_data_ind],
                         clust = re_prob_mat[full_data_ind,model_ind])
  final_df <- rbind(final_df,working_df)
}
  


sleep_df <- final_df
sleep_df$modelnum <- as.factor(sleep_df$modelnum)
sleep_df$pov <- as.factor(sleep_df$pov)
sleep_df$age <- as.factor(sleep_df$age)

sleep_df$clust <- as.factor(sleep_df$clust)
sleep_df$race <- as.factor(sleep_df$race)

sleep_df$gender <- as.factor(sleep_df$gender)
sleep_df$houseFS <- as.factor(sleep_df$houseFS)

sleep_df$bmi_disc <- as.factor(sleep_df$bmi_disc)
# sleep_df$bmi_cont <- as.factor(sleep_df$bmi_cont)


```

```{r}
# sleep_df <- sleep_df %>% filter(modelnum == 7)

sleep_df %>%
    # Specify group indicator, column, function
    group_by(modelnum,pov) %>%
    # Calculate the mean of the "Frequency" column for each group
    summarise_at(c("block", "onset", "eff", "totalSleep"), mean, na.rm = TRUE)

ggplot(sleep_df, aes(x=pov, y=block,)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=pov, y=onset)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=pov, y=eff)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=pov, y=totalSleep)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

```


```{r}

sleep_df %>%
    # Specify group indicator, column, function
    group_by(modelnum,age) %>%
    # Calculate the mean of the "Frequency" column for each group
    summarise_at(c("block", "onset", "eff", "totalSleep"), mean, na.rm = TRUE)

ggplot(sleep_df, aes(x=as.factor(age), y=block,)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=as.factor(age), y=onset)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=as.factor(age), y=eff)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=as.factor(age), y=totalSleep)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum)

```


```{r}


sleep_df %>%
    # Specify group indicator, column, function
    group_by(clust) %>%
    # Calculate the mean of the "Frequency" column for each group
    summarise_at(c("block", "onset", "eff", "totalSleep"), mean, na.rm = TRUE)


ggplot(sleep_df %>% filter(modelnum == 9), aes(x=clust, y=pov_cont)) + 
  geom_boxplot()

ggplot(sleep_df%>% filter(modelnum == 9), aes(x=clust, y=age_cont)) + 
  geom_boxplot(outlier.shape = NA)


ggplot(sleep_df%>% filter(modelnum == 9), aes(x=clust, y=block)) + 
  geom_boxplot()

ggplot(sleep_df%>% filter(modelnum == 9), aes(x=clust, y=onset)) + 
  geom_boxplot()

ggplot(sleep_df%>% filter(modelnum == 9), aes(x=clust, y=eff)) + 
  geom_boxplot()

ggplot(sleep_df%>% filter(modelnum == 9), aes(x=clust, y=totalSleep)) + 
  geom_boxplot()

```

```{r}
ggplot(sleep_df, aes(x=gender, y=block)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=gender, y=onset)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=gender, y=eff)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=gender, y=totalSleep)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)




ggplot(sleep_df, aes(x=bmi_disc, y=block)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=bmi_disc, y=onset)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=bmi_disc, y=eff)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=bmi_disc, y=totalSleep)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)


```

```{r}
nre.labs <- c("Individual HMM", "MHMM8 ")
names(nre.labs) <- c(1,9)
  

ggplot(sleep_df, aes(x=as.factor(age_cont), y=onset)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum,
             labeller = labeller(modelnum = nre.labs)) + 
  scale_x_discrete(breaks = seq(10,70,10))


ggplot(sleep_df, aes(x=as.factor(age_cont), y=totalSleep)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum,
             labeller = labeller(modelnum = nre.labs)) + 
  scale_x_discrete(breaks = seq(10,70,10))

ggplot(sleep_df, aes(x=as.factor(age_cont), y=eff)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=as.factor(age_cont), y=totalSleep)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum)+ scale_x_discrete(breaks = seq(10,70,10))

ggplot(sleep_df, aes(x=clust, y=age_cont)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=clust, y=bmi_cont)) + 
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~modelnum)

ggplot(sleep_df, aes(x=bmi_disc, y=eff)) + 
  geom_boxplot()+
  facet_wrap(~modelnum)

```

```{r}
library(lubridate)
library(zoo)


GetRollDF  <- function(var){
  roll_df <- data.frame()
  for (model_num in c(1,9)){
    roll <- 5
    lower_age <- 3 + floor(roll/2)
    upper_age <- 80 - floor(roll/2)
    
    line_df <- sleep_df %>% 
      filter(modelnum == model_num ) %>%
      group_by(age_cont) %>%
      summarise_at(c("block", "onset", "eff", "totalSleep"), quantile, probs = c(.05), na.rm = TRUE)
    
    
    roll_df_working <- data.frame(age = c(lower_age:upper_age),
                          modelnum = model_num)
    
    if (var == "onset"){
      roll_df_working <- roll_df_working %>% mutate(Q05 = seconds_to_period(900 * rollmean(pull(line_df, var),roll)))
    } else if (var == "totalSleep"){
      roll_df_working <- roll_df_working %>% mutate(Q05 = (1/60) * 15 * rollmean(pull(line_df, var),roll))
    } else {
      roll_df_working <- roll_df_working %>% mutate(Q05 = rollmean(pull(line_df, var),roll))
    }
    
    
    line_df <- sleep_df %>% 
      filter(modelnum == model_num ) %>% 
      group_by(age_cont) %>%
      summarise_at(c("block", "onset", "eff", "totalSleep"), quantile, probs = c(.5), na.rm = TRUE)
    
    if (var == "onset"){
      roll_df_working <- roll_df_working %>% mutate(Median = seconds_to_period(900 * pull(line_df, var) %>% rollmean(roll)))
    } else if (var == "totalSleep"){
      roll_df_working <- roll_df_working %>% mutate(Median = (1/60) * 15 * pull(line_df, var) %>% rollmean(roll))
    } else {
      roll_df_working <- roll_df_working %>% mutate(Median = pull(line_df, var) %>% rollmean(roll))
    }
    
    line_df <- sleep_df %>% 
      filter(modelnum == model_num ) %>% 
      group_by(age_cont) %>%
      summarise_at(c("block", "onset", "eff", "totalSleep"), quantile, probs = c(.95), na.rm = TRUE)
    
    
    
    
    if (var == "onset"){
      roll_df_working <- roll_df_working %>% mutate(Q95 = seconds_to_period(900 * pull(line_df, var) %>% rollmean(roll)))
    } else if (var == "totalSleep"){
      roll_df_working <- roll_df_working %>% mutate(Q95 = (1/60) * 15 * pull(line_df, var) %>% rollmean(roll))
    } else {
      roll_df_working <- roll_df_working %>% mutate(Q95 = pull(line_df, var) %>% rollmean(roll))
    }
    
    
    roll_df <- rbind(roll_df,roll_df_working)
  }
  
  if (var == "onset"){
    roll_df[,3] <- as.Date(roll_df[,3])
    roll_df[,4] <- as.Date(roll_df[,4])
    roll_df[,5] <- as.Date(roll_df[,5])
  }
    
  return(roll_df)
}




nre.labs <- c("Individual HMM", "MHMM8 ")
names(nre.labs) <- c(1,9)
  

roll_df <- GetRollDF("onset")
ggplot(data=roll_df, aes(x=age, y=Median))  + 
  geom_line(aes(col = as.factor(modelnum))) + 
  geom_ribbon(aes(ymin=Q05, ymax=Q95, fill = as.factor(modelnum)), linetype=1, alpha=0.3)+
  labs(x = "Age", y = "Sleep Onset",
       title = "Sleep Onset by Age for Individual and Mixed HMM",
       fill = "Model",
       col = "Model") + 
  scale_color_viridis(discrete=TRUE,end = .8,
                      labels=c("1" = "Ind HMM", "9"="MHMM8"))+
  scale_fill_viridis(discrete=TRUE,end = .8,
                     labels=c("1" = "Ind HMM", "9"="MHMM8"))+
  theme_bw()

# setwd("../Plots/")
# ggsave("RealOnset.png",scale = 1)


roll_df <- GetRollDF("eff")
ggplot(data=roll_df, aes(x=age, y=Median))  + 
  geom_line(aes(col = as.factor(modelnum))) + 
  geom_ribbon(aes(ymin=Q05, ymax=Q95, fill = as.factor(modelnum)), linetype=1, alpha=0.3)+
  labs(x = "Age", y = "Sleep Efficiency",
       title = "Sleep Efficiency by Age for Individual and Mixed HMM",
       fill = "Model",
       col = "Model") + 
  scale_color_viridis(discrete=TRUE,end = .8,
                      labels=c("1" = "Ind HMM", "9"="MHMM8"))+
  scale_fill_viridis(discrete=TRUE,end = .8,
                     labels=c("1" = "Ind HMM", "9"="MHMM8"))+
  theme_bw()


# setwd("../Plots/")
# ggsave("RealEff.png",scale = 1)
roll_df <- GetRollDF("totalSleep")
ggplot(data=roll_df, aes(x=age, y=Median))  + 
  geom_line(aes(col = as.factor(modelnum))) + 
  geom_ribbon(aes(ymin=Q05, ymax=Q95, fill = as.factor(modelnum)), linetype=1, alpha=0.3)+
  labs(x = "Age", y = "Daily Total Sleep",
       title = "Daily Total Sleep by Age for Individual and Mixed HMM",
       fill = "Model",
       col = "Model") + 
  scale_color_viridis(discrete=TRUE,end = .8,
                      labels=c("1" = "Ind HMM", "9"="MHMM8"))+
  scale_fill_viridis(discrete=TRUE,end = .8,
                     labels=c("1" = "Ind HMM", "9"="MHMM8"))+
  theme_bw()

# setwd("../Plots/")
# ggsave("RealTotal.png",scale = 1)





```



```{r}


load("/Users/aronjr/Documents/Predoc/ActivityHMM/ParseData/MeanRemovedNWAge/MHMM0.rda")


km <- kmeans(params_to_save[[7]][1,1,],
             centers = 4,algorithm="Lloyd",iter.max = 1000)

centers <- sort(km$centers)

km <- kmeans(params_to_save[[7]][1,1,],
             centers = centers,algorithm="Lloyd",iter.max = 10)

km$centers
act_est_array[[9]][1,1,]


sleep_df9 <- sleep_df %>% filter(modelnum == 9) %>% mutate(kgroup = as.factor(km$cluster[full_data_ind]))

ggplot(sleep_df9, aes(x=clust, y=age_cont)) + 
  geom_boxplot(outlier.shape = NA)

ggplot(sleep_df9, aes(x=kgroup, y=age_cont)) + 
  geom_boxplot(outlier.shape = NA)

ggplot(sleep_df9, aes(x=clust, y=bmi_cont)) + 
  geom_boxplot(outlier.shape = NA)

ggplot(sleep_df9, aes(x=kgroup, y=bmi_cont)) + 
  geom_boxplot(outlier.shape = NA)

table(sleep_df9$clust,sleep_df9$kgroup)
```

```{r}
library(mclust, quietly=TRUE)
fit = Mclust(params_to_save[[7]][1,1,], G=8, model="V")


table(sleep_df9$clust,fit$classification[full_data_ind])
```
