---
title: "Parse Data"
output: html_document
date: "2023-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# setwd("Routputs")
# file_list <- list.files()
# file_length <- length(file_list) - 1
# 
# init_est_array <- matrix(0,2,file_length)
# 
# tran_est_array <- array(0,dim = c(2,2,file_length))
# 
# light_est_array <- array(0,dim = c(2,2,file_length))
# 
# act_est_array <- array(0,dim = c(3,2,2,file_length))
# 
# cor_est_array <- matrix(0,2,file_length)
# 
# binom_est_array <- matrix(0,2,file_length)
# 
# for (file_ind in 1:file_length){
#   load(file_list[file_ind])
#   
#   init_est_array[,file_ind] <- params_to_save[[1]][[1]]
#   
#   tran_est_array[,,file_ind] <- params_to_save[[1]][[2]]
#   
#   light_est_array[,,file_ind] <- params_to_save[[1]][[3]]
#   
#   act_est_array[,,,file_ind] <- params_to_save[[1]][[4]]
#   
#   cor_est_array[,file_ind] <- params_to_save[[1]][[5]]
#   
#   binom_est_array[,file_ind] <- params_to_save[[1]][[6]]
#   
# }

load("Routputs/AHMMrace.rda")

params_tran <- params_to_save[[1]][[2]]
```

```{r}
library(ggplot2)
library(gridExtra)
library(stringr) 
library(tidyverse)

expit <- function(x){
  return(exp(x) / (1+exp(x)))
}

logit <- function(x){
  return(log(x/(1-x)))
}

Param2TranHelper <- function(p12,p21){
  tran <- matrix(0,2,2)
  tran[1,2] <- expit(p12)
  tran[1,1] <- 1- tran[1,2]
  tran[2,1] <- expit(p21)
  tran[2,2] <- 1 - tran[2,1]
  return(tran)
}

Params2Tran <- function(params_tran,time,index){
  param_matrix <- matrix(params_tran,ncol=8,nrow=2, byrow = T)
  if (index == 1){
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,7]*cos(2*pi*time/96)+param_matrix[1,8]*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,7]*cos(2*pi*time/96)+param_matrix[2,8]*sin(2*pi*time/96))
  } else {
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,index]+param_matrix[1,7]*cos(2*pi*time/96)+param_matrix[1,8]*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,index]+param_matrix[2,7]*cos(2*pi*time/96)+param_matrix[2,8]*sin(2*pi*time/96))
  }
  return(tran)
}

race_list <- c("0","1","2","3","4","5")
race_list <- c("Mexican American","Other Hispanic","NH White",
               "NH Black","NH Asian","Other Race - Including Multi-Racial")

tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=1)
tran_df <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                      type = rep(c("Sleep", "Wake"),each= 96),
                      time = rep(c(1:96)/4,2),
                      race = race_list[1])

for (i in 2:6){
  tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=i)
  tran_df_working <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                      type = rep(c("Sleep", "Wake"),each= 96),
                      time = rep(c(1:96)/4,2),
                      race = race_list[i])
  
  tran_df <- rbind(tran_df,tran_df_working)
}

  
#init
init <- params_to_save[[1]][[1]]

#emit 
emit_light <- params_to_save[[1]][[3]]

colnames(emit_light) <- c("Mean","Std Dev")
rownames(emit_light) <- c("Wake","Sleep")



emit_act <- params_to_save[[1]][[4]]
dimnames(emit_act)[[1]] <- c("Norm Act","Covar 1", "Covar 2")
dimnames(emit_act)[[2]] <- c("Mean","Std Dev")
dimnames(emit_act)[[3]] <- c("Wake","Sleep")

wake_sleep_cor <- params_to_save[[1]][[5]]
act_light_LoD <- params_to_save[[1]][[6]]
```

```{r, fig.width=10}



ggplot(tran_df %>% filter(type == "Sleep"), aes(x = time,y = prob, color = race)) + 
  geom_line() + 
  labs(title = "Probability of Falling Asleep by Hour", x = "Hour", y = "Probability of Falling Asleep")


ggplot(tran_df %>% filter(type == "Wake"), aes(x = time,y = prob, color = race)) + 
  geom_line() + 
  labs(title = "Probability of Waking by Hour", x = "Hour", y = "Probability of Waking")

init
emit_light
emit_act
wake_sleep_cor
act_light_LoD

```