---
title: "FindTime"
output: pdf_document
date: "2023-11-19"
---

```{r}

setwd("Sims/Student/Size1/c6/")
file_list <- list.files()




time_df <- data.frame()


for (file_ind in 1:length(file_list)){
  load(file_list[file_ind])
  init_cond <- params_to_save[[5]]
  
  dist <- init_cond[[4]]
  num_re <- init_cond[[5]]
  seed <- init_cond[[6]]
  time <- sum(init_cond[[7]])/60
  
  working_df <- data.frame(dist = dist,
                           num_re = as.factor(num_re),
                           seed = as.factor(seed),
                           time = time)
  
  time_df <- rbind(time_df,working_df)
  
}

library(ggplot2)
library(dplyr)

ggplot(time_df, aes(x=num_re, y=time)) +
  geom_boxplot() + facet_wrap(vars(dist))
```

```{r}

n <- 300000

plot(density(rnorm(n,0,2)),xlim = c(-20,20),ylim = c(0,.5))
# lines(density(c(-rgamma(n/2,1,.5),rgamma(n/2,1,.5))),col = "red")
# plot(density(c(rnorm(n*2/3,-1,1),rgamma(n/3,2,1)-0)+2),col = "blue",xlim = c(-10,10),ylim = c(0,.4))
plot(density(c(rnorm(n/2,1,2),-rgamma(n/4,4,2),runif(n/4,-2,2))),col = "blue",xlim = c(-10,10),ylim = c(0,.4))
# lines(density(c(rnorm(n/2,-2,2),rgamma(n/2,2,1))),col = "red")

```