---
title: "ParseMultiSim"
output: html_document
date: "2023-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo =FALSE}
library(dplyr)
library(ggplot2)

expit <- function(x){
  to_ret <- exp(x) / (1+exp(x))
  if (is.na(to_ret)){return(1)}
  return(to_ret)
}

logit <- function(x){
  return(log(x/(1-x)))
}

Param2TranHelper <- function(p12,p21){
  tran <- matrix(0,2,2)
  tran[1,2] <- expit(p12)
  tran[1,1] <- 1- tran[1,2]
  tran[2,1] <- expit(p21)
  tran[2,2] <- 1 - tran[2,1]
  return(tran)
}
  
Params2Tran <- function(params_tran,time,index){
  
  harmonic_ind <- ((index*2)-1)+6
  #####by row is different here
  param_matrix <- matrix(params_tran,ncol=18,nrow=2, byrow = F)
  if (index == 1){
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,7]*cos(2*pi*time/96)+param_matrix[1,8]*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,7]*cos(2*pi*time/96)+param_matrix[2,8]*sin(2*pi*time/96))
  } else {
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,index]+
                               (param_matrix[1,7]+param_matrix[1,harmonic_ind])*cos(2*pi*time/96)+
                               (param_matrix[1,8]+param_matrix[1,harmonic_ind+1])*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,index]+
                               (param_matrix[2,7]+param_matrix[2,harmonic_ind])*cos(2*pi*time/96)+
                               (param_matrix[2,8]+param_matrix[2,harmonic_ind+1])*sin(2*pi*time/96))
  }
  return(tran)
}


tran_covar_num <- 3

Tran2DF <- function(params_tran){
  race_list <- c("0","1","2","3","4","5") 
  
  tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=1)
  tran_df <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[1])
  
  for (i in 2:tran_covar_num){
    tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=i)
    tran_df_working <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[i])
    
    tran_df <- rbind(tran_df,tran_df_working)
  }
  
  return(tran_df)
}
  

ParseSingleClust <- function(folder, path_size ){
  setwd(path_size)
  setwd(folder)
  # setwd("Size1/c8/")
  

  file_list <- list.files()
  load(file_list[1])
  
  num_re <- params_to_save[[5]][[5]]
  
  num_re_ind <- num_re
  if(num_re == 0){num_re_ind <- 1}

    
  
  init_true_array <- matrix(0,2,length(file_list))
  init_est_array <- matrix(0,2,length(file_list))
  
  param_tran_true_array <- array(0,dim = c(2,18,length(file_list)))
  param_tran_est_array <- array(0,dim = c(2,18,length(file_list)))
  
  # light_true_array <- array(0,dim = c(2,2,length(file_list)))
  # light_est_array <- array(0,dim = c(2,2,length(file_list)))
  
  act_true_array <- array(0,dim = c(2,2,num_re_ind,length(file_list)))
  act_est_array <- array(0,dim = c(2,2,num_re_ind,length(file_list)))
  
  # cor_true_array <- matrix(0,2,length(file_list))
  # cor_est_array <- matrix(0,2,length(file_list))
  
  binom_true_array <- matrix(0,2,length(file_list))
  binom_est_array <- matrix(0,2,length(file_list))
  
  pil_true_array <- matrix(0,num_re_ind,length(file_list))
  pil_est_array <- matrix(0,num_re_ind,length(file_list))
  
  flike <- c()
  like_array <- c()
  neg_step <- c()
  
  vit_array <- matrix(0,5,length(file_list))
  
  time_array <- matrix(0,1,length(file_list))
  
  
  IC_est_array <- matrix(0,2,length(file_list))
  
  # tran_df_array <- array(0,dim = c(dim(params_to_save[[6]][[2]])[1],
  #                                  dim(params_to_save[[6]][[2]])[2],length(file_list)))
  
  
  nap_array <- matrix(0,1,length(file_list))
  
  for (file_ind in 1:length(file_list)){
    load(file_list[file_ind])
    
    init_true_array[,file_ind] <- params_to_save[[1]][[1]]
    init_est_array[,file_ind] <- params_to_save[[2]][[1]]
    
    param_tran_true_array[,,file_ind] <- matrix(params_to_save[[1]][[2]],2,18,byrow = T) 
    param_tran_est_array[,,file_ind] <- matrix(params_to_save[[2]][[2]],2,18,byrow = T) 
    
    # light_true_array[,,file_ind] <- params_to_save[[1]][[3]]
    # light_est_array[,,file_ind] <- params_to_save[[2]][[3]]
    
    act_true_array[,,,file_ind] <- params_to_save[[1]][[3]]
    act_est_array[,,,file_ind] <- params_to_save[[2]][[3]]
    
    # cor_true_array[,file_ind] <- params_to_save[[1]][[5]]
    # cor_est_array[,file_ind] <- params_to_save[[2]][[5]]
    
    
    binom_true_array[,file_ind] <- params_to_save[[1]][[4]]
    binom_est_array[,file_ind] <- params_to_save[[2]][[4]]
    
    # pil_true_array[,file_ind] <- params_to_save[[1]][[5]]
    pil_est_array[,file_ind] <- params_to_save[[2]][[5]]
    
    
    flike <- c(flike,params_to_save[[3]][length(params_to_save[[3]])])
    like_array <- diff(params_to_save[[3]])
    neg_step <- c(neg_step,like_array[like_array < 0])
    # print(neg_step)
  
    
    vit_array[1,file_ind] <- params_to_save[[4]][[3]]
    vit_array[2,file_ind] <- params_to_save[[4]][[4]]
    vit_array[3,file_ind] <- params_to_save[[4]][[5]]
    vit_array[4,file_ind] <- params_to_save[[4]][[6]]
    vit_array[5,file_ind] <- params_to_save[[4]][[7]]
    
    time_array[file_ind] <- sum(params_to_save[[5]][[7]])
    
    # tran_df_array[,,file_ind] <- params_to_save[[6]][[2]]
    
    
    IC_est_array[,file_ind] <- params_to_save[[7]]
    
  }
  
  act_true_array[1,1,,] <- 0
  

  
  tran_med <- apply(param_tran_est_array,c(1,2),median)
  
  tran_df_est <- Tran2DF(tran_med)
  tran_df_est <- tran_df_est %>% mutate(etype = num_re)
  
  tran_df_true <- Tran2DF(param_tran_true_array[,,1])
  tran_df_true <- tran_df_true %>% mutate(etype = "true")
  
  tran_df <- rbind(tran_df_est,tran_df_true)
  
  # x <- tran_df
  # tran_df <- rbind(x,tran_df_est)
  
  init_cond <-  params_to_save[[5]]
  
  # tran_resid <-  params_to_save[[6]]
  
  return(list(list(init_true_array,init_est_array),
              list(param_tran_true_array,param_tran_est_array),
              list(act_true_array,act_est_array),
              list(binom_true_array,binom_est_array),
              list(pil_true_array,pil_est_array),
              list(flike,neg_step),
              tran_df,
              num_re,
              vit_array,
              init_cond,
              time_array,
              IC_est_array))
  
  setwd("..")
}




ParseSingleSim <- function(path_size){
  setwd(path_size)
  folder_list <- list.files()
  SingleSim <- list()
  for (folder_ind in 1:length(folder_list)){
    SingleClust <- ParseSingleClust(folder_list[folder_ind],path_size)
    SingleSim <- append(SingleSim,list(SingleClust))
  }
  return(SingleSim)
}


ParseSingleTypeMultiSize <- function(path_type){
  setwd(path_type)
  folder_list <- list.files()
  SingleType_MultiSize <- list()
  for(folder_ind in 1:length(folder_list)){
    path_type_size <- paste0(path_type,"/",folder_list[folder_ind])
    SingleSim <- ParseSingleSim(path_type_size)
    SingleType_MultiSize <- append(SingleType_MultiSize,list(SingleSim))
  }
  return(SingleType_MultiSize)
}

ParseSims <- function(path){
  setwd(path)
  folder_list <- list.files()
  MultiSim <- list()
  for(folder_ind in 1:length(folder_list)){
    path_type <- paste0(path,"/",folder_list[folder_ind])
    SingleType_MultiSize <- ParseSingleTypeMultiSize(path_type)
    MultiSim <- append(MultiSim,list(SingleType_MultiSize))
  }
  
  return(MultiSim)
}

path_size <- "/Users/aronjr/Documents/Predoc/ActivityHMM/ParseSims/Sim/Norm/Size4"
# SingleSim <- ParseSingleSim(path_size)  

path_type <- "/Users/aronjr/Documents/Predoc/ActivityHMM/ParseSims/Sim/Stud3nt/"
# SingleType_MultiSize <- ParseSingleTypeMultiSize(path_type)

 
path <- "/Users/aronjr/Documents/Predoc/ActivityHMM/ParseSims/Sim/"
MultiSim <- ParseSims(path)



```


```{r}
  


# SingleSim[[1]][[10]]
# SingleType_MultiSize[[2]][[1]][[10]]
# MultiSim[[2]][[2]][[1]][[10]]
# 
# 
# SingleType_MultiSize[[1]][[1]][[2]][[2]][,,57]
# 
# SingleSim <- MultiSim[[2]][[2]]
clust_num <- 8
dist_num <- length(MultiSim)
final_df <- data.frame()

for (dist_ind in 1:dist_num){
  size_num <- length(MultiSim[[dist_ind]])
  for (size_ind in 1:size_num){
    for (clust_ind in 1:(clust_num+1)){
      nRE <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[8]]
      vit_med <- apply(MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[9]],1,median)
      nobs <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[3]][1]
      lobs <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[3]][2]
      dist <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[4]]
      
      working_df <- data.frame(estimates = vit_med,
                             accType = c("Total","Wake Sensitivity","Sleep Sensitivity","Wake PPV","Sleep PPV"),
                             numberRE = nRE,
                             numObs = nobs,
                             lenObs = lobs,
                             dist = dist)
      final_df <- rbind(final_df,working_df)
    }
  }
  
}

library(tidyr)


library(looplot)

vit_df <- final_df %>% pivot_wider(names_from = numberRE, values_from = estimates,names_prefix = "Cluster") 

vit_df <- vit_df%>% mutate(xfiller = 1) 

colnames(vit_df)[1] <- "Accuracy Type"
colnames(vit_df)[2] <- "Number of Participants"
colnames(vit_df)[3] <- "Days of Follow-Up"
colnames(vit_df)[4] <- "Distribution"

vit_df <- vit_df %>% mutate(Distribution = case_when(Distribution == "gamma" ~ "Gamma",
                                                     Distribution == "norm" ~ "Normal",
                                                     Distribution == "student" ~ "t(df=2)",
                                                     Distribution == "mix1" ~ "Mixture1",
                                                     Distribution == "mix2" ~ "Mixture2",
                                                     Distribution == "stud3nt" ~ "t(df=3)",
                                                     Distribution == "unif" ~ "Uniform"))


vit_df$Distribution <- factor(vit_df$Distribution, levels = c("Gamma", "Normal","Uniform", "Mixture1","Mixture2","t(df=3)","t(df=2)"))
vit_df$`Accuracy Type` <- factor(vit_df$`Accuracy Type`, levels = c("Sleep PPV","Sleep Sensitivity","Total","Wake Sensitivity","Wake PPV"))

#Only focus on sensitivity 
#Comment out this line for results on PPV too
# vit_df <- vit_df %>% filter(.[[1]] != "Wake PPV" & .[[1]] != "Sleep PPV")
```


```{r}
acc_df <- vit_df %>% filter(.[[1]] == "Total")
acc_df <- acc_df[,-1]
vit_df <- vit_df %>% filter(.[[1]] != "Total")

vit_df <- vit_df %>% mutate(State = rep(c("Wake","Sleep"),dim(vit_df)[1]/2))
vit_df <- vit_df %>% mutate(Type = rep(c("Sensitivity","Sensitivity","PPV","PPV"),dim(vit_df)[1]/4))
vit_df <- vit_df[,-1]

vit_df$State <- factor(vit_df$State, levels = c("Wake", "Sleep"))
vit_df$Type <- factor(vit_df$Type, levels = c("Sensitivity", "PPV"))
```


```{r,fig.height=9,fig.width=9}

# vit_df <- vit_df[,c(-1)]


# plot_data = nested_loop_base_data(
#     vit_df,
#     x = "xfiller", steps = c("Days of Follow-Up","Distribution"),
#     # x = "xfiller", steps = c("Days of Follow-Up","Number of Participants"),
#     grid_cols = c("Type"),
#     grid_rows = c("State"),
#     spu_x_shift = 2,
#     replace_labels = list("Days of Follow-Up" = c("96" = "1",
#                                         "672" = "7")),
# )

plot_data = nested_loop_base_data(
    vit_df,
    x = "xfiller", steps = c("Number of Participants","Days of Follow-Up","Distribution"),
    # x = "xfiller", steps = c("Days of Follow-Up","Number of Participants"),
    grid_cols = c("Type"),
    grid_rows = c("State"),
    spu_x_shift = 2,
    replace_labels = list("Days of Follow-Up" = c("96" = "1",
                                        "672" = "7"),
                          "Number of Participants" = c("1000" = "1k",
                                        "5000" = "5k")
                          ),
)

p = nested_loop_base_plot(
    plot_data,
    x_name = "", 
    y_name = "Rate",
    colors = viridis::viridis(11)[c(1,3:10)],
    shapes = c(17,15,16,16,16,16,16,16,16),
    sizes = c(2,1,1,1,1,1,1,1,1),
    legend_labels = c("Individual Emission HMM",
                      "Shared Emission HMM","MHMM2","MHMM3",
                      "MHMM4","MHMM5","MHMM6",
                      "MHMM7","MHMM8"),
    connect_spus = T
)

plot_data = nested_loop_paramsteps_data(
    plot_data,
    steps_y_base = 0.225, steps_y_height = .05, steps_y_shift = .1
)

p = nested_loop_paramsteps_plot(
    p, plot_data, 
    steps_values_annotate = TRUE, 
    steps_annotation_size = 2.5
)

p = add_processing(
    p, 
    list(
        # set limits
        adjust_ylim = list(
            y_expand_add = c(-0.05, NULL)
        ),
        # adjust theme
        add_custom_theme = list(
            axis.text.x=element_blank(), 
            axis.ticks.x=element_blank(),
            legend.position = "top", 
            panel.grid.major = element_line(
              color = "grey65", size = 0.1
            )
        )
    )
)

p + labs(title = "Sensitivity and PPV by Model, Sample Size, and RE Distribution") 

#+ guides(size = F, shape = F, linetype = F)

# setwd("../Plots")
# ggsave("NestedLoopSP.png",width = 9,height = 9)
```


```{r,fig.height=9,fig.width=9}

# acc_df <- acc_df[,c(-1)]

# plot_data = nested_loop_base_data(
#     acc_df,
#     x = "xfiller", steps = c("Days of Follow-Up","Distribution"),
#     spu_x_shift = 2,
#     replace_labels = list("Days of Follow-Up" = c("96" = "1",
#                                         "672" = "7")),
# )


plot_data = nested_loop_base_data(
    acc_df,
    x = "xfiller", steps = c("Number of Participants","Days of Follow-Up","Distribution"),
    spu_x_shift = 2,
    replace_labels = list("Days of Follow-Up" = c("96" = "1",
                                        "672" = "7"),
                          "Number of Participants" = c("1000" = "1k",
                                        "5000" = "5k")
                          ),
)


p = nested_loop_base_plot(
    plot_data,
    x_name = "", 
    y_name = "Rate",
    colors = viridis::viridis(11)[c(1,3:10)],
    shapes = c(17,15,16,16,16,16,16,16,16),
    sizes = c(1.5,1.5,1,1,1,1,1,1,1),
    legend_labels = c("Individual Emission HMM",
                      "Shared Emission HMM","MHMM2","MHMM3",
                      "MHMM4","MHMM5","MHMM6",
                      "MHMM7","MHMM8"),
    connect_spus = T
)

plot_data = nested_loop_paramsteps_data(
    plot_data,
    steps_y_base = 0.5, steps_y_height = .025, steps_y_shift = .05
)

p = nested_loop_paramsteps_plot(
    p, plot_data, 
    steps_values_annotate = TRUE, 
    steps_annotation_size = 2.5
)

p = add_processing(
    p, 
    list(
        # set limits
        adjust_ylim = list(
            y_expand_add = c(-0.05, NULL)
        ),
        # adjust theme
        add_custom_theme = list(
            axis.text.x=element_blank(), 
            axis.ticks.x=element_blank(),
            legend.position = "top", 
            panel.grid.major = element_line(
              color = "grey65", size = 0.1
            )
        ), 
        # add horizontal lines
        add_abline = list(
            intercept = 0
        )
    )
)

p + labs(title = "Total Accuracy by Model, Sample Size, and RE Distribution") 

# setwd("../Plots")
# ggsave("NestedLoopAcc.png",width = 7,height = 5)
```


```{r}
dist_num <- length(MultiSim)
final_df <- data.frame()

Q10 <- function(x){return(quantile(x,probs = c(.1)))}
Q25 <- function(x){return(quantile(x,probs = c(.25)))}
Q75 <- function(x){return(quantile(x,probs = c(.75)))}
Q90 <- function(x){return(quantile(x,probs = c(.9)))}
Q95 <- function(x){return(quantile(x,probs = c(.95)))}

for (dist_ind in 1:dist_num){
  size_num <- length(MultiSim[[dist_ind]])
  for (size_ind in 1:size_num){
    for (clust_ind in 1:(clust_num+1)){
      nRE <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[8]]
      nobs <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[3]][1]
      lobs <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[3]][2]
      dist <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[4]]
      
      
      tran_df_working <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[7]] %>% 
        pivot_wider(names_from = etype, values_from = prob,names_prefix = "Cluster")
      colnames(tran_df_working)[4:5] <- c("est","true")
      
      tran_df_working <- tran_df_working %>% 
        mutate(resid = abs(est - true)) %>% 
        group_by(type,race) %>% 
        # summarise(across(resid,list(Q25 = Q25)))
        # summarise(across(resid,list(med = median)))
        summarise(across(resid,list(Q90 = Q90)))
        # summarise(median = median(resid))
      
      colnames(tran_df_working)[3] <- "quantile"
      
      working_df <- data.frame(estimates = tran_df_working$quantile,
                             Transition = tran_df_working$type,
                             Covariate = tran_df_working$race,
                             numberRE = nRE,
                             numObs = nobs,
                             lenObs = lobs,
                             dist = dist)
      final_df <- rbind(final_df,working_df)
    }
  }
  
}



tran_resid_df <- final_df %>% pivot_wider(names_from = numberRE, values_from = estimates,names_prefix = "Cluster") 

tran_resid_df <- tran_resid_df%>% mutate(xfiller = 1) 


colnames(tran_resid_df)[1] <- "Transition"
colnames(tran_resid_df)[2] <- "Covariate"
colnames(tran_resid_df)[3] <- "Number of Participants"
colnames(tran_resid_df)[4] <- "Days of Follow-Up"
colnames(tran_resid_df)[5] <- "Distribution"


tran_resid_df <- tran_resid_df %>% mutate(Distribution = case_when(Distribution == "gamma" ~ "Gamma",
                                                     Distribution == "norm" ~ "Normal",
                                                     Distribution == "student" ~ "t(df=2)",
                                                     Distribution == "mix1" ~ "Mixture1",
                                                     Distribution == "mix2" ~ "Mixture2",
                                                     Distribution == "stud3nt" ~ "t(df=3)",
                                                     Distribution == "unif" ~ "Uniform"))


tran_resid_df$Distribution <- factor(tran_resid_df$Distribution, levels = c("Gamma", "Normal","Uniform", "Mixture1","Mixture2","t(df=3)","t(df=2)"))


tran_resid_df <- tran_resid_df %>% mutate(Transition = case_when(Transition == "Sleep" ~ "Wake to Sleep",
                                                                 Transition == "Wake" ~ "Sleep to Wake"))



```

```{r,fig.height=9,fig.width=9}

# tran_resid_df <- tran_resid_df[,-c(3)]

# plot_data = nested_loop_base_data(
#     tran_resid_df,
#     x = "xfiller", steps = c("Days of Follow-Up","Distribution"),
#     grid_cols = c("Transition"),
#     grid_rows = c("Covariate"),
#     spu_x_shift = 2,
#     replace_labels = list("Days of Follow-Up" = c("96" = "1",
#                                         "672" = "7")),
# )

plot_data = nested_loop_base_data(
    tran_resid_df,
    x = "xfiller", steps = c("Number of Participants","Days of Follow-Up","Distribution"),
    grid_cols = c("Transition"),
    grid_rows = c("Covariate"),
    spu_x_shift = 2,
    replace_labels = list("Days of Follow-Up" = c("96" = "1",
                                        "672" = "7"),
                          "Number of Participants" = c("1000" = "1k",
                                        "5000" = "5k")
                          ),
)

p = nested_loop_base_plot(
    plot_data,
    x_name = "", 
    y_name = "90th Percentile Absolute Transition Residual",
    colors = viridis::viridis(11)[c(1,3:10)],
    shapes = c(17,15,16,16,16,16,16,16,16),
    sizes = c(1.5,1.5,1,1,1,1,1,1,1),
    legend_labels = c("Individual Emission HMM",
                      "Shared Emission HMM","MHMM2","MHMM3",
                      "MHMM4","MHMM5","MHMM6",
                      "MHMM7","MHMM8"),
    connect_spus = T
)

plot_data = nested_loop_paramsteps_data(
    plot_data,
    steps_y_base = -0.05, steps_y_height = .025, steps_y_shift = .075
)

p = nested_loop_paramsteps_plot(
    p, plot_data, 
    steps_values_annotate = TRUE, 
    steps_annotation_size = 2.5
)

p = add_processing(
    p, 
    list(
        # set limits
        adjust_ylim = list(
            y_expand_add = c(.05, NULL)
        ),
        # adjust theme
        add_custom_theme = list(
            axis.text.x=element_blank(), 
            axis.ticks.x=element_blank(),
            legend.position = "top", 
            panel.grid.major = element_line(
              color = "grey65", size = 0.1
            )
        ), 
        # add horizontal lines
        add_abline = list(
            intercept = 0
        )
    )
)



p + labs(title = "Transition Residuals by Model, Sample Size, and RE Distribution") 

setwd("../Plots")
ggsave("NestedLoopTran.png",width = 9,height = 9)
```


```{r}
dist_num <- length(MultiSim)
final_df <- data.frame()

for (dist_ind in 1:dist_num){
  size_num <- length(MultiSim[[dist_ind]])
  for (size_ind in 1:size_num){
    for (clust_ind in 1:(clust_num+1)){
      
      nRE <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[8]]
      time <- max(MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[11]])
      nobs <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[3]][1]
      lobs <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[3]][2]
      dist <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[4]]
      
      working_df <- data.frame(estimates = time/60/60,
                             numberRE = nRE,
                             numObs = nobs,
                             lenObs = lobs,
                             dist = dist)
      final_df <- rbind(final_df,working_df)
    }
  }
  
}

time_df <- final_df %>% pivot_wider(names_from = numberRE, values_from = estimates,names_prefix = "Cluster") 

time_df <- time_df%>% mutate(xfiller = 1) 


colnames(time_df)[1] <- "Number of Participants"
colnames(time_df)[2] <- "Days of Follow-Up"
colnames(time_df)[3] <- "Distribution"

time_df <- time_df %>% mutate(Distribution = case_when(Distribution == "gamma" ~ "Gamma",
                                                                 Distribution == "norm" ~ "Normal",
                                                                 Distribution == "student" ~ "t(df=2)",
                                                                 Distribution == "stud3nt" ~ "t(df=3)",
                                                                 Distribution == "mix1" ~ "Mixture1",
                                                                 Distribution == "mix2" ~ "Mixture2",
                                                                 Distribution == "unif" ~ "Uniform"))


time_df$Distribution <- factor(time_df$Distribution, levels = c("Gamma", "Normal","Uniform", "Mixture1","Mixture2","t(df=3)","t(df=2)"))


```


```{r,fig.height=9,fig.width=9}
# time_df <- time_df[,-c(1)]


# plot_data = nested_loop_base_data(
#     time_df,
#     x = "xfiller", steps = c("Days of Follow-Up","Distribution"),
#     spu_x_shift = 2,
#     replace_labels = list("Days of Follow-Up" = c("96" = "1",
#                                         "672" = "7")),
# )

plot_data = nested_loop_base_data(
    time_df,
    x = "xfiller", steps = c("Number of Participants","Days of Follow-Up","Distribution"),
    spu_x_shift = 2,
    replace_labels = list("Days of Follow-Up" = c("96" = "1",
                                        "672" = "7"),
                          "Number of Participants" = c("1000" = "1k",
                                        "5000" = "5k")
                          ),
)

p = nested_loop_base_plot(
    plot_data,
    x_name = "", 
    y_name = "Median Running Time (Hours)",
    colors = viridis::viridis(11)[c(1,3:10)],
    shapes = c(17,15,16,16,16,16,16,16,16),
    sizes = c(1.5,1.5,1,1,1,1,1,1,1),
    legend_labels = c("Individual Emission HMM",
                      "Shared Emission HMM","MHMM2","MHMM3",
                      "MHMM4","MHMM5","MHMM6",
                      "MHMM7","MHMM8"),
    connect_spus = T
)

plot_data = nested_loop_paramsteps_data(
    plot_data,
    steps_y_base = -.3, steps_y_height = .25, steps_y_shift = .6
)

p = nested_loop_paramsteps_plot(
    p, plot_data, 
    steps_values_annotate = TRUE, 
    steps_annotation_size = 2.5
)

p = add_processing(
    p, 
    list(
        # set limits
        adjust_ylim = list(
            y_expand_add = c(NULL, NULL)
        ),
        # adjust theme
        add_custom_theme = list(
            axis.text.x=element_blank(), 
            axis.ticks.x=element_blank(),
            legend.position = "top", 
            panel.grid.major = element_line(
              color = "grey65", size = 0.1
            )
        )
    )
)

p + labs(title = "Median Running Time by Model, Sample Size, and RE Distribution")

# setwd("../Plots")
# ggsave("NestedLoopCompTime.png",width = 7,height = 7)
```



```{r}
dist_num <- length(MultiSim)
final_df <- data.frame()

for (dist_ind in 1:dist_num){
  size_num <- length(MultiSim[[dist_ind]])
  for (size_ind in 1:size_num){
    for (clust_ind in 1:(clust_num+1)){
      
      nRE <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[8]]
      bic <- median(MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[12]][2,])
      # bic <- median(MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[3]][[2]][2,2,1,])-2
      nobs <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[3]][1]
      lobs <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[3]][2]
      dist <- MultiSim[[dist_ind]][[size_ind]][[clust_ind]][[10]][[4]]
      
      working_df <- data.frame(estimates = bic,
                             numberRE = nRE,
                             numObs = nobs,
                             lenObs = lobs,
                             dist = dist)
      final_df <- rbind(final_df,working_df)
    }
  }
  
}

bic_df <- final_df %>% pivot_wider(names_from = numberRE, values_from = estimates,names_prefix = "Cluster") 

bic_df <- bic_df%>% mutate(xfiller = 1) 


colnames(bic_df)[1] <- "Number of Participants"
colnames(bic_df)[2] <- "Days of Follow-Up"
colnames(bic_df)[3] <- "Distribution"

bic_df <- bic_df %>% mutate(Distribution = case_when(Distribution == "gamma" ~ "Gamma",
                                                                 Distribution == "norm" ~ "Normal",
                                                                 Distribution == "student" ~ "t(df=2)",
                                                                 Distribution == "stud3nt" ~ "t(df=3)",
                                                                 Distribution == "mix1" ~ "Mixture1",
                                                                 Distribution == "mix2" ~ "Mixture2",
                                                                 Distribution == "unif" ~ "Uniform"))


bic_df$Distribution <- factor(bic_df$Distribution, levels = c("Gamma", "Normal","Uniform", "Mixture1","Mixture2","t(df=3)","t(df=2)"))


```


```{r,fig.height=9,fig.width=9}
# time_df <- time_df[,-c(1)]


# plot_data = nested_loop_base_data(
#     time_df,
#     x = "xfiller", steps = c("Days of Follow-Up","Distribution"),
#     spu_x_shift = 2,
#     replace_labels = list("Days of Follow-Up" = c("96" = "1",
#                                         "672" = "7")),
# )

plot_data = nested_loop_base_data(
    bic_df,
    x = "xfiller", steps = c("Number of Participants","Days of Follow-Up","Distribution"),
    spu_x_shift = 2,
    replace_labels = list("Days of Follow-Up" = c("96" = "1",
                                        "672" = "7"),
                          "Number of Participants" = c("1000" = "1k",
                                        "5000" = "5k")
                          ),
)

p = nested_loop_base_plot(
    plot_data,
    x_name = "", 
    y_name = "Median Running Time (Hours)",
    colors = viridis::viridis(11)[c(1,3:10)],
    shapes = c(17,15,16,16,16,16,16,16,16),
    sizes = c(1.5,1.5,1,1,1,1,1,1,1),
    legend_labels = c("Individual Emission HMM",
                      "Shared Emission HMM","MHMM2","MHMM3",
                      "MHMM4","MHMM5","MHMM6",
                      "MHMM7","MHMM8"),
    connect_spus = T
)

plot_data = nested_loop_paramsteps_data(
    plot_data,
    # steps_y_base = -1.5e7, steps_y_height = 3e5, steps_y_shift = 6e5
    steps_y_base = -.8, steps_y_height = .025, steps_y_shift = .075
)

p = nested_loop_paramsteps_plot(
    p, plot_data, 
    steps_values_annotate = TRUE, 
    steps_annotation_size = 2.5
)

p = add_processing(
    p, 
    list(
        # set limits
        adjust_ylim = list(
            y_expand_add = c(NULL, NULL)
        ),
        # adjust theme
        add_custom_theme = list(
            axis.text.x=element_blank(), 
            axis.ticks.x=element_blank(),
            legend.position = "top", 
            panel.grid.major = element_line(
              color = "grey65", size = 0.1
            )
        )
    )
)

p + labs(title = "Median Running Time by Model, Sample Size, and RE Distribution")

# setwd("../Plots")
# ggsave("NestedLoopBIC.png",width = 7,height = 7)
```




```{r}
dgamma1 <- function(x,shape,rate){
  return(dgamma(x+2,shape,rate))
}
  
mix1 <- function(x,shape,rate,mean,sd){
  return(.5*dgamma(x,shape,rate) + .5*dnorm(x,mean,sd))
}

p1 <- ggplot(data = data.frame(x = c(-7.5,7.5)), aes(x)) +
  stat_function(fun = dnorm, n = 10000, 
                args = list(mean = init_cond[[1]][1], sd = init_cond[[1]][2]),
                aes(colour = "Wake"))  +
  stat_function(fun = dnorm, n = 10000, 
                args = list(mean = init_cond[[2]][1], sd = init_cond[[2]][2]),
                aes(colour = "Sleep"))  +
  scale_y_continuous(breaks = NULL) +
  labs(x = "Distribution of Activity", y="", title="Distribution of Activity by Wake-Sleep State",color="Wake-Sleep State") +
  scale_color_viridis(discrete=TRUE,end = .8)+
  theme_bw() +
  theme(legend.position = "top") 


setwd("../Plots")
ggsave("ActDist.png",width = 6,height = 3)

p2 <- ggplot(data = data.frame(x = c(-8, 8)), aes(x)) +
  scale_y_continuous(breaks = NULL) +
  labs(x = "Random Effect", y="", title="Random Effect Distribution (H)") + 
  stat_function(fun = dnorm, n = 10000, args = list(mean = 0, sd = 2),aes(color = "Normal")) +
  geom_function(fun = dgamma1, args = list(shape = 2, rate = 1),aes(color = "Gamma")) +
  geom_function(fun = mix1, args = list(shape = 2, rate = 1,mean = -2,sd = 2), 
                aes(color = "Normal/Gamma")) + 
  stat_function(fun = dt, n = 10000, args = list(df=2), aes(color = "t (df = 2)")) +
  labs(color = "Distribution") + 
  theme_bw() + 
  theme(legend.position = "top")+
  scale_color_viridis(discrete=TRUE,end = .85)

setwd("../Plots")
ggsave("HDist.png",width = 6,height = 3)


```





