---
title: "ParseSims GMM4 Random Start"
output: pdf_document
date: "2023-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo =FALSE}
library(dplyr)
library(ggplot2)

expit <- function(x){
  return(exp(x) / (1+exp(x)))
}

logit <- function(x){
  return(log(x/(1-x)))
}

Param2TranHelper <- function(p12,p21){
  tran <- matrix(0,2,2)
  tran[1,2] <- expit(p12)
  tran[1,1] <- 1- tran[1,2]
  tran[2,1] <- expit(p21)
  tran[2,2] <- 1 - tran[2,1]
  return(tran)
}

Params2Tran <- function(params_tran,time,index){
  param_matrix <- matrix(params_tran,ncol=8,nrow=2, byrow = F)
  if (index == 1){
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,7]*cos(2*pi*time/96)+
                               param_matrix[1,8]*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,7]*cos(2*pi*time/96)+
                               param_matrix[2,8]*sin(2*pi*time/96))
  } else {
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,index]+param_matrix[1,7]*cos(2*pi*time/96)+
                               param_matrix[1,8]*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,index]+param_matrix[2,7]*cos(2*pi*time/96)+
                               param_matrix[2,8]*sin(2*pi*time/96))
  }
  return(tran)
}


tran_covar_num <- 3

Tran2DF <- function(params_tran){
  race_list <- c("0","1","2","3","4","5") 
  
  
  tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=1)
  tran_df <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[1])
  
  for (i in 2:tran_covar_num){
    tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=i)
    tran_df_working <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[i])
    
    tran_df <- rbind(tran_df,tran_df_working)
  }
  
  return(tran_df)
}
  

ParseSingleClust <- function(folder, path){
  setwd(path)
  setwd(folder)

  file_list <- list.files()
  load(file_list[1])
  
  
  num_re <- dim(params_to_save[[1]][[3]])[3]
  
  init_true_array <- matrix(0,2,length(file_list))
  init_est_array <- matrix(0,2,length(file_list))
  
  param_tran_true_array <- array(0,dim = c(2,8,length(file_list)))
  param_tran_est_array <- array(0,dim = c(2,8,length(file_list)))
  
  # light_true_array <- array(0,dim = c(2,2,length(file_list)))
  # light_est_array <- array(0,dim = c(2,2,length(file_list)))
  
  act_true_array <- array(0,dim = c(2,2,num_re,length(file_list)))
  act_est_array <- array(0,dim = c(2,2,num_re,length(file_list)))
  
  # cor_true_array <- matrix(0,2,length(file_list))
  # cor_est_array <- matrix(0,2,length(file_list))
  
  binom_true_array <- matrix(0,1,length(file_list))
  binom_est_array <- matrix(0,1,length(file_list))
  
  pil_true_array <- matrix(0,num_re,length(file_list))
  pil_est_array <- matrix(0,num_re,length(file_list))
  
  flike <- c()
  like_array <- c()
  neg_step <- c()
  
  vit_array <- matrix(0,5,length(file_list))
  
  for (file_ind in 1:length(file_list)){
    load(file_list[file_ind])
    
    init_true_array[,file_ind] <- params_to_save[[1]][[1]]
    init_est_array[,file_ind] <- params_to_save[[2]][[1]]
    
    param_tran_true_array[,,file_ind] <- params_to_save[[1]][[2]][c(1,9,2,10,3,11,4,12,5,13,6,14,7,15,8,16)]
    param_tran_est_array[,,file_ind] <- params_to_save[[2]][[2]][c(1,9,2,10,3,11,4,12,5,13,6,14,7,15,8,16)]
    
    # light_true_array[,,file_ind] <- params_to_save[[1]][[3]]
    # light_est_array[,,file_ind] <- params_to_save[[2]][[3]]
    
    act_true_array[,,,file_ind] <- params_to_save[[1]][[3]]
    act_est_array[,,,file_ind] <- params_to_save[[2]][[3]]
    
    # cor_true_array[,file_ind] <- params_to_save[[1]][[5]]
    # cor_est_array[,file_ind] <- params_to_save[[2]][[5]]
    
    
    binom_true_array[file_ind] <- params_to_save[[1]][[4]]
    binom_est_array[file_ind] <- params_to_save[[2]][[4]]
    
    # pil_true_array[,file_ind] <- params_to_save[[1]][[5]]
    pil_est_array[,file_ind] <- params_to_save[[2]][[5]]
    
    
    flike <- c(flike,params_to_save[[3]][length(params_to_save[[3]])])
    like_array <- diff(params_to_save[[3]])
    neg_step <- c(neg_step,like_array[like_array < 0])
    # print(neg_step)
  
    
    vit_array[1,file_ind] <- params_to_save[[4]][[3]]
    vit_array[2,file_ind] <- params_to_save[[4]][[4]]
    vit_array[3,file_ind] <- params_to_save[[4]][[5]]
    vit_array[4,file_ind] <- params_to_save[[4]][[6]]
    vit_array[5,file_ind] <- params_to_save[[4]][[7]]
    
  }
  
  act_true_array[1,1,,] <- 0
  

  
  tran_med <- apply(param_tran_est_array,c(1,2),median)
  
  tran_df_est <- Tran2DF(tran_med)
  tran_df_est <- tran_df_est %>% mutate(etype = num_re)
  
  tran_df_true <- Tran2DF(param_tran_true_array[,,1])
  tran_df_true <- tran_df_true %>% mutate(etype = "true")
  
  tran_df <- rbind(tran_df_est,tran_df_true)
  
  # x <- tran_df
  # tran_df <- rbind(x,tran_df_est)
  
  init_cond <-  params_to_save[[5]]
  
  return(list(list(init_true_array,init_est_array),
              list(param_tran_true_array,param_tran_est_array),
              list(act_true_array,act_est_array),
              list(binom_true_array,binom_est_array),
              list(pil_true_array,pil_est_array),
              list(flike,neg_step),
              tran_df,
              num_re,
              vit_array,
              init_cond))
  
  setwd("..")
}




ParseSingleSim <- function(path){
  setwd(path)
  folder_list <- list.files()
  SingleSim <- list()
  for (folder_ind in 1:length(folder_list)){
    SingleClust <- ParseSingleClust(folder_list[folder_ind],path)
    SingleSim <- append(SingleSim,list(SingleClust))
  }
  return(SingleSim)
}


path_size <- "C:/Users/jorda/Documents/Grad School/Research/ActivityHMM/ParseSims/Sims/norm/Size4/"
SingleSim <- ParseSingleSim(path_size)  


```

```{r, echo =FALSE}
library(ggplot2)
library(gridExtra)



SimBoxplot <- function(SingleSim,list_ind,est_ind,vec_ind1, inc_true,title,vec_ind2 = NA){

  num_of_sims <- length(SingleSim)
  final_df <- data.frame()
  
  for (sim_ind in 1:num_of_sims){
    if(vec_ind1 == 0){
      est <- SingleSim[[sim_ind]][[list_ind]][[est_ind]]
    } else if (is.na(vec_ind2)){
      est <- SingleSim[[sim_ind]][[list_ind]][[est_ind]][vec_ind1,]
    } else {
      est <- SingleSim[[sim_ind]][[list_ind]][[est_ind]][vec_ind1,vec_ind2,1,]
    } 
      
    if (length(est) > 0){
      nRE <- SingleSim[[sim_ind]][[8]]
      
      working_df <- data.frame(estimates = est,
                               numberRE = nRE)
      final_df <- rbind(final_df,working_df)
    }
  }
  
  final_df$numberRE <- factor(final_df$numberRE,levels = c(sort(unique(final_df$numberRE))))
  
  
  if (inc_true){
    if (is.na(vec_ind2)){
      est <- SingleSim[[1]][[list_ind]][[1]][vec_ind1,]
    } else{
      est <- SingleSim[[1]][[list_ind]][[1]][vec_ind1,vec_ind2,1,]
    }
      
    nRE <- "Truth"
    working_df <- data.frame(estimates = est,
                             numberRE = nRE)
    final_df <- rbind(final_df,working_df)
  }
    
  
  
  ggplot(final_df, aes(x=numberRE, y=estimates)) +
    geom_boxplot() +
    ggtitle(title)+coord_cartesian(ylim = quantile(final_df$estimates, c(0.025, 0.975)))
}

TranPlot <- function(df,wake_sleep, diff = F){
  if(wake_sleep == "Sleep"){
    title <- "Probability of Falling Asleep by Hour"
  } else if (wake_sleep == "Wake"){
    title <- "Probability of Waking by Hour"
  }
  
  if (diff){title <- paste("Residuals for",title)}
  
  
  p <- ggplot(df %>% filter(type == wake_sleep), aes(x = time,y = prob,  color = etype)) + 
    geom_line() + 
    labs(title = title, x = "Hour", y = "Probability of Falling Asleep")+
    facet_grid(rows = vars(race))
  
  if (diff){p <- p + geom_hline(yintercept=0, linetype="dashed")}
  
  return(p)
}

PlotTran <- function(SingleSim){
  num_of_sims <- length(SingleSim)
  final_df <- data.frame()
  
  for (sim_ind in 1:num_of_sims){
    final_df <- rbind(final_df,SingleSim[[sim_ind]][[7]])
  }
  
  p1 <- TranPlot(final_df,"Sleep")
  p2 <- TranPlot(final_df,"Wake")
  
  diff_df <- final_df %>% filter(etype != "true")
  diff_df <- diff_df %>% mutate(prob = final_df[final_df$etype!="true",1] - final_df[final_df$etype=="true",1])
  
  p3 <- TranPlot(diff_df,"Sleep",diff = T)
  p4 <- TranPlot(diff_df,"Wake",diff = T)
  
  return(list(p1,p2,p3,p4))
}



BoxplotClust <- function(list_ind,inc_out = T){
  final_df <- data.frame()
  num_of_sims <- length(SingleSim)
  
  if (list_ind == 3){
    ylabel <- "Cluster Mean"
    xlabel <- ""
    title <- "Cluster Mean and Mixing Proportion by Number of Support Points"
  }
  if (list_ind == 5){
    ylabel <- "Mixing Proportion"
    xlabel <- "Cluster Index"
    title <- ""
    }
  
  for (sim_ind in 1:num_of_sims){
      nRE <- SingleSim[[sim_ind]][[8]]
      
      if (length(dim(SingleSim[[sim_ind]][[list_ind]][[2]])) == 4){
        working_ms <- SingleSim[[sim_ind]][[list_ind]][[2]][1,1,,]
      } else {
        working_ms <- SingleSim[[sim_ind]][[list_ind]][[2]]
      }
        
    
      
      if (!is.null(dim(working_ms)[1])){
        for (clust_ind in 1:dim(working_ms)[1]){
          working_df <- data.frame(estimates = working_ms[clust_ind,],
                                   numberRE = nRE,
                                   clust_ind = clust_ind)
          
          final_df <- rbind(final_df,working_df)
        }
        
      } else {
        working_df <- data.frame(estimates = SingleSim[[sim_ind]][[list_ind]][[2]][1,1,1,],
                                 numberRE = nRE,
                                 clust_ind = 1)
        
        final_df <- rbind(final_df,working_df)
    }
  }
    
  final_df$numberRE <- factor(final_df$numberRE,levels = c(sort(unique(final_df$numberRE))))
  final_df$clust_ind <- factor(final_df$clust_ind,levels = c(sort(unique(final_df$clust_ind))))
  
  
  p <- ggplot(final_df, aes(x=clust_ind, y=estimates)) +
    facet_grid(cols = vars(numberRE)) + 
    labs(x = xlabel, y = ylabel,  title = title) +
    geom_boxplot()
  
  if(!inc_out){p <- p +coord_cartesian(ylim = quantile(final_df$estimates, c(0.025, 0.975)))}
  
  return(p)

}

DecodeBoxplot <- function(SingleSim,title){

  num_of_sims <- length(SingleSim)
  final_df <- data.frame()
  
  for (sim_ind in 1:num_of_sims){
    nRE <- SingleSim[[sim_ind]][[8]]
    
    working_df <- data.frame(estimates = as.vector(SingleSim[[sim_ind]][[9]]),
                             accType = rep(c("Both","Wake","Sleep"),dim(SingleSim[[sim_ind]][[9]])[2]),
                             numberRE = nRE)
    final_df <- rbind(final_df,working_df)
  }
  
  final_df$numberRE <- factor(final_df$numberRE,levels = c(sort(unique(final_df$numberRE))))
  
  
    
  
  
  ggplot(final_df, aes(x=accType, y=estimates, color = accType)) +
    geom_boxplot()+
    facet_grid(cols = vars(numberRE)) +
    labs(x = "Activity Type", y = "Percent Correcly Predicted")+ 
    guides(color="none") + 
    ggtitle(title)
}
    
  
```


```{r,fig.width=10, fig.height = 7.5, echo =FALSE}

init_cond <- SingleSim[[1]][[10]]

p1 <- ggplot(data = data.frame(x = c(-8, 13)), aes(x)) +
  stat_function(fun = dnorm, n = 10000, args = list(mean = init_cond[[2]][1], sd = init_cond[[2]][2]), 
                 aes(colour = "Sleep Activity"))  +
  stat_function(fun = dnorm, n = 10000, args = list(mean = init_cond[[1]][1], sd = init_cond[[1]][2]), 
                 aes(colour = "Wake Activity"))  +
  #scale_y_continuous(breaks = NULL) +
  labs(x = "Activity", y="", title="True Activity by State") + theme(legend.position="bottom")

p2 <- ggplot(data = data.frame(x = c(-8, 13)), aes(x)) +
    #scale_y_continuous(breaks = NULL) +
    labs(x = "RE", y="", title="True RE Distribution")

if (init_cond[[4]] == "norm"){
  p2 <- p2 + stat_function(fun = dnorm, n = 10000, args = list(mean = 0, sd = 2)) 
} else if (init_cond[[4]] == "gamma"){
  
  dgamma1 <- function(x,shape,rate){
    return(dgamma(x+2,shape,rate))
  }
  
  mix1 <- function(x,shape,rate,mean,sd){
    return(.5*dgamma(x,shape,rate) + .5*dnorm(x,mean,sd))
  }
  
  p2 <- p2 + geom_function(fun = dgamma1, args = list(shape = 2, rate = 1))
} else if (init_cond[[4]] == "student"){
  p2 <- p2 + stat_function(fun = dt, n = 10000, args = list(df=2))
}

  




tran_plots <- PlotTran(SingleSim)
tran_plots[[1]]
tran_plots[[3]]

tran_plots[[2]]
tran_plots[[4]]


grid.arrange(BoxplotClust(3,F),
             BoxplotClust(5),nrow=2)



DecodeBoxplot(SingleSim,"Prediction By Activity Type and Number of Clusters")

grid.arrange(SimBoxplot(SingleSim,1,2,2,T,"Initial Probability"),
             SimBoxplot(SingleSim,3,2,1,T,"Wake Activity SE",2),
             SimBoxplot(SingleSim,3,2,2,T,"Sleep Activity",1),
             SimBoxplot(SingleSim,3,2,2,T,"Sleep Activity SE",2),
             ncol= 2)





SimBoxplot(SingleSim,6,2,0,F,"Likelihood Step Decreases")
```


```{r}
# 
# init_cond <- SingleSim[[1]][[10]]
# 
# p1 <- ggplot(data = data.frame(x = c(-5, 10)), aes(x)) +
#   stat_function(fun = dnorm, n = 10000, args = list(mean = init_cond[[2]][1], sd = init_cond[[2]][2]), 
#                  aes(colour = "Sleep Activity"))  +
#   stat_function(fun = dnorm, n = 10000, args = list(mean = init_cond[[1]][1], sd = init_cond[[1]][2]), 
#                  aes(colour = "Wake Activity"))  +
#   #scale_y_continuous(breaks = NULL) +
#   labs(x = "Activity", y="", title="True Activity by State",color="Activity Type") + theme(legend.position = c(.91,.5))
# 
# 
# p2 <- ggplot(data = data.frame(x = c(-5, 10)), aes(x)) +
#     #scale_y_continuous(breaks = NULL) +
#     labs(x = "RE", y="", title="True RE Distribution")
# 
# 
# p3 <- p2 + stat_function(fun = dnorm, n = 10000, args = list(mean = 0, sd = 2),aes(color = "Normal")) +
#   geom_function(fun = dgamma1, args = list(shape = 2, rate = 1),aes(color = "Gamma")) +
#   geom_function(fun = mix1, args = list(shape = 2, rate = 1,mean = -2,sd = 2), aes(color = "Normal/Gamma")) +
#   labs(color = "RE Distribution") + theme(legend.position = c(.91,.5))
# 
# 
# p4 <- p2 + stat_function(fun = dt, n = 10000, args = list(df=2), aes(color = "t (df = 2)"))+
#   stat_function(fun = dt, n = 10000, args = list(df=3), aes(color = "t (df = 3)")) +
#   labs(color = "RE Distribution") + theme(legend.position = c(.91,.5))
# 
# 
# g <- grid.arrange(p1,p3,p4,
#              ncol= 1)
# 
# g <- arrangeGrob(p1,p3,p4, nrow=3) #generates g
# 
# ggsave(file="REdist.png", g)

ggsave(file="clustmeanmix.png", g)
```


```{r}
KL <- function(param1,param2){
  mu1 <- param1[1]
  sig1 <- param1[2]
  mu2 <- param2[1]
  sig2 <- param2[2]
  
  return(log(sig2/sig1)+(sig1^2 + (mu1-mu2)^2)/(2*sig2^2) - 1/2)
}

KL(c(0,2),c(6,3))


KL(c(0,2),c(2,3))

# Error in serverSocket(port = port) : 
#   creation of server socket failed: port 11475 cannot be opened
# Calls: makeCluster -> makePSOCKcluster -> serverSocket
# Execution halted

# x <- seq(0,2*pi,.1)
# b1 <- seq(-1,-.8,.1)
# b2 <- seq(.8,1,.1)
# b3 <- seq(-.6,-.4,.1)
# b4 <- seq(.4,.6,.1)
# 
#   for(i1 in 1:length(b1)){
#     for(i2 in 1:length(b2)){
#       for(i3 in 1:length(b1)){
#         for(i4 in 1:length(b2)){
#           plot(b1[i1]*cos(x) + b2[i2]*sin(x)+b3[i3]*cos(2*x) + b4[i4]*sin(2*x),type = "l",
#                main = paste(b1[i1],b2[i2],b3[i3],b4[i4]))
#         }
#       }
#   }
#   }

b1 <- -.8
b2 <- 1
b3 <- -.5
b4 <- .4

plot(b1*cos(x) + b2*sin(x)+b3*cos(2*x) + b4*sin(2*x),type = "l")

```

