---
title: "ParseSims Trans Covar"
output: pdf_document
date: "2023-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("test5/")
file_list <- list.files()

# file_list <- file_list[-c(36 ,69 ,151 ,196 ,197 ,228, 238)]

num_re <- 3

init_true_array <- matrix(0,2,length(file_list))
init_est_array <- matrix(0,2,length(file_list))

param_tran_true_array <- array(0,dim = c(2,8,length(file_list)))
param_tran_est_array <- array(0,dim = c(2,8,length(file_list)))

light_true_array <- array(0,dim = c(2,2,length(file_list)))
light_est_array <- array(0,dim = c(2,2,length(file_list)))

act_true_array <- array(0,dim = c(3,2,2,length(file_list)))
act_est_array <- array(0,dim = c(3,2,2,length(file_list)))

cor_true_array <- matrix(0,2,length(file_list))
cor_est_array <- matrix(0,2,length(file_list))

binom_true_array <- matrix(0,2,length(file_list))
binom_est_array <- matrix(0,2,length(file_list))

reset_true_array <- matrix(0,num_re,length(file_list))
reset_est_array <- matrix(0,num_re,length(file_list))

pil_true_array <- matrix(0,num_re,length(file_list))
pil_est_array <- matrix(0,num_re,length(file_list))

like_array <- matrix(0,1,length(file_list))

for (file_ind in 1:length(file_list)){
  load(file_list[file_ind])
  
  init_true_array[,file_ind] <- params_to_save[[1]][[1]]
  init_est_array[,file_ind] <- params_to_save[[2]][[1]]
  
  param_tran_true_array[,,file_ind] <- params_to_save[[1]][[2]][c(1,9,2,10,3,11,4,12,5,13,6,14,7,15,8,16)]
  param_tran_est_array[,,file_ind] <- params_to_save[[2]][[2]][c(1,9,2,10,3,11,4,12,5,13,6,14,7,15,8,16)]
  
  light_true_array[,,file_ind] <- params_to_save[[1]][[3]]
  light_est_array[,,file_ind] <- params_to_save[[2]][[3]]
  
  act_true_array[,,,file_ind] <- params_to_save[[1]][[4]]
  act_est_array[,,,file_ind] <- params_to_save[[2]][[4]]
  
  cor_true_array[,file_ind] <- params_to_save[[1]][[5]]
  cor_est_array[,file_ind] <- params_to_save[[2]][[5]]
  
  
  binom_true_array[,file_ind] <- params_to_save[[1]][[6]]
  binom_est_array[,file_ind] <- params_to_save[[2]][[6]]
  
  reset_true_array[,file_ind] <- params_to_save[[1]][[7]]
  reset_est_array[,file_ind] <- params_to_save[[2]][[7]]
  
  pil_true_array[,file_ind] <- params_to_save[[1]][[8]]
  pil_est_array[,file_ind] <- params_to_save[[2]][[8]]
  
  
  like_array[,file_ind] <- params_to_save[[3]][length(params_to_save[[3]])]
  
}
```

```{r}
library(ggplot2)
library(gridExtra)

AnalyzeResids <- function(true_array,est_array, index1, index2 = NA, title, index3 = NA){
  
  if (is.na(index2)){
    df <- data.frame(resid = est_array[index1,] - true_array[index1,])
    true_mean <- mean(true_array[index1,])
  } else if (is.na(index3)){
    df <- data.frame(resid = est_array[index1,index2,] - true_array[index1,index2,])
    true_mean <- true_array[index1,index2,]
  } else {
    if (index2 == 2){est_array[index1,index2,index3,] <- abs(est_array[index1,index2,index3,])}
    df <- data.frame(resid = est_array[index1,index2,index3,] - true_array[index1,index2,index3,])
    true_mean <- true_array[index1,index2,index3,]
  }
  
    binwid <- (max(df) - min(df))/12
    title <- paste("Residuals for",title)
  
  ggplot(df, aes(x = resid)) + 
    geom_histogram(colour="black", fill="white", binwidth = binwid)+
    geom_vline(aes(xintercept=0),
              color="blue", size=1) + 
    geom_vline(aes(xintercept=mean(resid)),
              color="red", linetype="dashed", size=1) + 
    xlab("Residuals") + 
    ggtitle(title, subtitle = paste("True Mean of Parameter is ",round(true_mean,2))) + 
    theme_gray()
  
}

```

```{r, fig.width=10}

grid.arrange(AnalyzeResids(init_true_array,init_est_array,1,title = "Initial Wake"),
             AnalyzeResids(init_true_array,init_est_array,2,title = "Initial Sleep"),
             nrow = 1)

  
grid.arrange(AnalyzeResids(param_tran_true_array,param_tran_est_array,1,1,"Wake to Sleep Base Transition"),
             AnalyzeResids(param_tran_true_array,param_tran_est_array,2,1,"Sleep to Wake Base Transition"),
             nrow = 1)  

grid.arrange(AnalyzeResids(param_tran_true_array,param_tran_est_array,1,2,"Wake to Sleep Race Covar 1"),
             AnalyzeResids(param_tran_true_array,param_tran_est_array,2,2,"Sleep to Wake Race Covar 1"),
             nrow = 1)

grid.arrange(AnalyzeResids(param_tran_true_array,param_tran_est_array,1,3,"Wake to Sleep Race Covar 2"),
             AnalyzeResids(param_tran_true_array,param_tran_est_array,2,3,"Sleep to Wake Race Covar 2"),
             nrow = 1)

grid.arrange(AnalyzeResids(param_tran_true_array,param_tran_est_array,1,4,"Wake to Sleep Race Covar 3"),
             AnalyzeResids(param_tran_true_array,param_tran_est_array,2,4,"Sleep to Wake Race Covar 3"),
             nrow = 1)

grid.arrange(AnalyzeResids(param_tran_true_array,param_tran_est_array,1,5,"Wake to Sleep Race Covar 4"),
             AnalyzeResids(param_tran_true_array,param_tran_est_array,2,5,"Sleep to Wake Race Covar 4"),
             nrow = 1)

grid.arrange(AnalyzeResids(param_tran_true_array,param_tran_est_array,1,6,"Wake to Sleep Race Covar 5"),
             AnalyzeResids(param_tran_true_array,param_tran_est_array,2,6,"Sleep to Wake Race Covar 5"),
             nrow = 1)

grid.arrange(AnalyzeResids(param_tran_true_array,param_tran_est_array,1,7,"Wake to Sleep Cosine"),
             AnalyzeResids(param_tran_true_array,param_tran_est_array,2,7,"Sleep to Wake Cosine"),
             nrow = 1)

grid.arrange(AnalyzeResids(param_tran_true_array,param_tran_est_array,1,8,"Wake to Sleep Sine"),
             AnalyzeResids(param_tran_true_array,param_tran_est_array,2,8,"Sleep to Wake Sine"),
             nrow = 1)


grid.arrange(AnalyzeResids(light_true_array,light_est_array,1,1,"Wake Light Mean"),
             AnalyzeResids(light_true_array,light_est_array,1,2,"Wake Light SE"),
             nrow = 1)

grid.arrange(AnalyzeResids(light_true_array,light_est_array,2,1,"Sleep Light Mean"),
             AnalyzeResids(light_true_array,light_est_array,2,2,"Sleep Light SE"),
             nrow = 1)



grid.arrange(AnalyzeResids(act_true_array,act_est_array,1,1,"Wake Activity Mean",1),
             AnalyzeResids(act_true_array,act_est_array,1,2,"Wake Activity SE",1),
             nrow = 1)
grid.arrange(AnalyzeResids(act_true_array,act_est_array,2,1,"Wake Activity Covar 1 Mean",1),
             AnalyzeResids(act_true_array,act_est_array,3,1,"Wake Activity Covar 2 Mean",1),
             nrow = 1)

grid.arrange(AnalyzeResids(act_true_array,act_est_array,1,1,"Sleep Activity Mean",2),
             AnalyzeResids(act_true_array,act_est_array,1,2,"Sleep Activity SE",2),
             nrow = 1)
grid.arrange(AnalyzeResids(act_true_array,act_est_array,2,1,"Sleep Activity Covar 1 Mean",2),
             AnalyzeResids(act_true_array,act_est_array,3,1,"Sleep Activity Covar 2 Mean",2), 
             nrow = 1)



grid.arrange(AnalyzeResids(cor_true_array,cor_est_array,1,title = "Wake Correlation"),
             AnalyzeResids(cor_true_array,cor_est_array,2,title = "Sleep Correlation"),
             nrow = 1)

grid.arrange(AnalyzeResids(binom_true_array,binom_est_array,1,title = "Act LoD"),
             AnalyzeResids(binom_true_array,binom_est_array,2,title = "Light LoD"),
             nrow = 1)


grid.arrange(AnalyzeResids(reset_true_array,reset_est_array,1,title = "RE1"),
             AnalyzeResids(reset_true_array,reset_est_array,2,title = "RE2"),
             AnalyzeResids(reset_true_array,reset_est_array,3,title = "RE3"),
             nrow = 1)




grid.arrange(AnalyzeResids(pil_true_array,pil_est_array,1,title = "Pi1"),
             AnalyzeResids(pil_true_array,pil_est_array,2,title = "Pi2"),
             AnalyzeResids(pil_true_array,pil_est_array,3,title = "Pi3"),
             nrow = 1)


hist(like_array)

```


```{r}
labswap <- which(like_array < -4230000)

reset_est_array[,labswap]
pil_est_array[,labswap]
```