---
title: "Simulation Check"
output: pdf_document
date: "2023-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo =FALSE}
library(dplyr)
library(ggplot2)
library(viridis)

expit <- function(x){
  return(exp(x) / (1+exp(x)))
}

logit <- function(x){
  return(log(x/(1-x)))
}

Param2TranHelper <- function(p12,p21){
  tran <- matrix(0,2,2)
  tran[1,2] <- expit(p12)
  tran[1,1] <- 1- tran[1,2]
  tran[2,1] <- expit(p21)
  tran[2,2] <- 1 - tran[2,1]
  return(tran)
}

Params2Tran <- function(params_tran,time,index){
  
  harmonic_ind <- ((index*2)-1)+6
  #####by row is different here
  param_matrix <- matrix(params_tran,ncol=18,nrow=2, byrow = F)
  if (index == 1){
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,7]*cos(2*pi*time/96)+param_matrix[1,8]*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,7]*cos(2*pi*time/96)+param_matrix[2,8]*sin(2*pi*time/96))
  } else {
    tran <- Param2TranHelper(param_matrix[1,1]+param_matrix[1,index]+
                               (param_matrix[1,7]+param_matrix[1,harmonic_ind])*cos(2*pi*time/96)+
                               (param_matrix[1,8]+param_matrix[1,harmonic_ind+1])*sin(2*pi*time/96),
                             param_matrix[2,1]+param_matrix[2,index]+
                               (param_matrix[2,7]+param_matrix[2,harmonic_ind])*cos(2*pi*time/96)+
                               (param_matrix[2,8]+param_matrix[2,harmonic_ind+1])*sin(2*pi*time/96))
  }
  return(tran)
}


tran_covar_num <- 3

Tran2DF <- function(params_tran){
  race_list <- c("0","1","2","3","4","5") 
  
  
  tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=1)
  tran_df <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[1])
  
  for (i in 2:tran_covar_num){
    tran_vec <- sapply(c(1:96),FUN = Params2Tran,params_tran = params_tran,index=i)
    tran_df_working <- data.frame(prob = c(tran_vec[3,],tran_vec[2,]),
                        type = rep(c("Sleep", "Wake"),each= 96),
                        time = rep(c(1:96)/4,2),
                        race = race_list[i])
    
    tran_df <- rbind(tran_df,tran_df_working)
  }
  
  return(tran_df)
}
  

ParseSingleClust <- function(folder, path){
  setwd(path)
  setwd(folder)
  # setwd("Sim/Norm/Size3/c0/")

  file_list <- list.files()
  load(file_list[1])
  
  
  num_re <- params_to_save[[5]][[5]]
  
  num_re_ind <- num_re
  if(num_re == 0){num_re_ind <- 1}
  
  init_true_array <- matrix(0,2,length(file_list))
  init_est_array <- matrix(0,2,length(file_list))
  
  param_tran_true_array <- array(0,dim = c(2,18,length(file_list)))
  param_tran_est_array <- array(0,dim = c(2,18,length(file_list)))
  
  # light_true_array <- array(0,dim = c(2,2,length(file_list)))
  # light_est_array <- array(0,dim = c(2,2,length(file_list)))
  
  act_true_array <- array(0,dim = c(2,2,num_re_ind,length(file_list)))
  act_est_array <- array(0,dim = c(2,2,num_re_ind,length(file_list)))
  
  # cor_true_array <- matrix(0,2,length(file_list))
  # cor_est_array <- matrix(0,2,length(file_list))
  
  binom_true_array <- matrix(0,2,length(file_list))
  binom_est_array <- matrix(0,2,length(file_list))
  
  pil_true_array <- matrix(0,num_re_ind,length(file_list))
  pil_est_array <- matrix(0,num_re_ind,length(file_list))
  
  flike <- c()
  like_array <- c()
  neg_step <- c()
  
  vit_array <- matrix(0,5,length(file_list))
  
  for (file_ind in 1:length(file_list)){
    load(file_list[file_ind])
    
    init_true_array[,file_ind] <- params_to_save[[1]][[1]]
    init_est_array[,file_ind] <- params_to_save[[2]][[1]]
    
    param_tran_true_array[,,file_ind] <- matrix(params_to_save[[1]][[2]],2,18,byrow = T) 
    param_tran_est_array[,,file_ind] <- matrix(params_to_save[[2]][[2]],2,18,byrow = T) 
    
    # light_true_array[,,file_ind] <- params_to_save[[1]][[3]]
    # light_est_array[,,file_ind] <- params_to_save[[2]][[3]]
    
    act_true_array[,,,file_ind] <- params_to_save[[1]][[3]]
    act_est_array[,,,file_ind] <- params_to_save[[2]][[3]]
    
    # cor_true_array[,file_ind] <- params_to_save[[1]][[5]]
    # cor_est_array[,file_ind] <- params_to_save[[2]][[5]]
    
    
    binom_true_array[,file_ind] <- params_to_save[[1]][[4]]
    binom_est_array[,file_ind] <- params_to_save[[2]][[4]]
    
    # pil_true_array[,file_ind] <- params_to_save[[1]][[5]]
    pil_est_array[,file_ind] <- params_to_save[[2]][[5]]
    
    
    flike <- c(flike,params_to_save[[3]][length(params_to_save[[3]])])
    like_array <- diff(params_to_save[[3]])
    neg_step <- c(neg_step,like_array[like_array < 0])
    # print(neg_step)
  
    
    vit_array[1,file_ind] <- params_to_save[[4]][[3]]
    vit_array[2,file_ind] <- params_to_save[[4]][[4]]
    vit_array[3,file_ind] <- params_to_save[[4]][[5]]
    vit_array[4,file_ind] <- params_to_save[[4]][[6]]
    vit_array[5,file_ind] <- params_to_save[[4]][[7]]
    
  }
  
  act_true_array[1,1,,] <- 0
  

  
  tran_med <- apply(param_tran_est_array,c(1,2),median)
  
  tran_df_est <- Tran2DF(tran_med)
  tran_df_est <- tran_df_est %>% mutate(etype = num_re)
  
  tran_df_true <- Tran2DF(param_tran_true_array[,,1])
  tran_df_true <- tran_df_true %>% mutate(etype = "true")
  
  tran_df <- rbind(tran_df_est,tran_df_true)
  
  # x <- tran_df
  # tran_df <- rbind(x,tran_df_est)
  
  init_cond <-  params_to_save[[5]]
  
  return(list(list(init_true_array,init_est_array),
              list(param_tran_true_array,param_tran_est_array),
              list(act_true_array,act_est_array),
              list(binom_true_array,binom_est_array),
              list(pil_true_array,pil_est_array),
              list(flike,neg_step),
              tran_df,
              num_re,
              vit_array,
              init_cond))
  
  setwd("..")
}




ParseSingleSim <- function(path){
  setwd(path)
  folder_list <- list.files()
  SingleSim <- list()
  for (folder_ind in 1:length(folder_list)){
    SingleClust <- ParseSingleClust(folder_list[folder_ind],path)
    SingleSim <- append(SingleSim,list(SingleClust))
  }
  return(SingleSim)
}


path_size <- "/Users/aronjr/Documents/Predoc/ActivityHMM/ParseSims/Sim/Gamma/Size1"
SingleSim <- ParseSingleSim(path_size)  


```

```{r, echo =FALSE}
library(ggplot2)
library(gridExtra)



SimBoxplot <- function(SingleSim,list_ind,est_ind,vec_ind1, inc_true,title,vec_ind2 = NA){

  num_of_sims <- length(SingleSim)
  final_df <- data.frame()
  
  for (sim_ind in 1:num_of_sims){
    if(vec_ind1 == 0){
      est <- SingleSim[[sim_ind]][[list_ind]][[est_ind]]
    } else if (is.na(vec_ind2)){
      est <- SingleSim[[sim_ind]][[list_ind]][[est_ind]][vec_ind1,]
    } else {
      est <- SingleSim[[sim_ind]][[list_ind]][[est_ind]][vec_ind1,vec_ind2,1,]
    } 
      
    if (length(est) > 0){
      nRE <- SingleSim[[sim_ind]][[8]]
      
      working_df <- data.frame(estimates = est,
                               numberRE = nRE)
      final_df <- rbind(final_df,working_df)
    }
  }
  
  final_df$numberRE <- factor(final_df$numberRE,levels = c(sort(unique(final_df$numberRE))))
  
  
  if (inc_true){
    if (is.na(vec_ind2)){
      est <- SingleSim[[1]][[list_ind]][[1]][vec_ind1,]
    } else{
      est <- SingleSim[[1]][[list_ind]][[1]][vec_ind1,vec_ind2,1,]
    }
      
    # nRE <- "Truth"
    # working_df <- data.frame(estimates = est,
    #                          numberRE = nRE)
    # final_df <- rbind(final_df,working_df)
    truth <- median(est)
  }
    
  
  
  ggplot(final_df, aes(x=numberRE, y=estimates)) +
    geom_boxplot(outlier.shape = NA) +
    ggtitle(title)+
    # coord_cartesian(ylim = quantile(final_df$estimates, c(0.0125, 0.9875)))+ 
    scale_y_continuous(limits = quantile(final_df$estimates, c(0.015, 0.985))) + 
    scale_x_discrete(breaks=c(0:8),
        labels=c("Ind HMM",
                 "Shared HMM","MHMM2","MHMM3",
                 "MHMM4","MHMM5","MHMM6",
                 "MHMM7","MHMM8")) +
  xlab("") + 
  ylab("Estimate")+
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, vjust = 1, hjust=1)) +
  geom_hline(yintercept = truth, linetype="dotted")
}

TranPlot <- function(df,wake_sleep, diff = F){
  if(wake_sleep == "Sleep"){
    title <- "Probability of Falling Asleep by Hour"
  } else if (wake_sleep == "Wake"){
    title <- "Probability of Waking by Hour"
  }
  
  if (diff){title <- paste("Residuals for",title)}
  
  
  p <- ggplot(df %>% filter(type == wake_sleep), aes(x = time,y = prob,  color = etype)) + 
    geom_line() + 
    labs(title = title, x = "Hour", y = "Probability of Falling Asleep")+
    facet_grid(rows = vars(race)) + 
    scale_color_viridis(discrete=TRUE)
  
  if (diff){p <- p + geom_hline(yintercept=0, linetype="dashed")}
  
  return(p)
}

PlotTran <- function(SingleSim){
  num_of_sims <- length(SingleSim)
  final_df <- data.frame()
  
  for (sim_ind in 1:num_of_sims){
    final_df <- rbind(final_df,SingleSim[[sim_ind]][[7]])
  }
  
  p1 <- TranPlot(final_df,"Sleep")
  p2 <- TranPlot(final_df,"Wake")
  
  diff_df <- final_df %>% filter(etype != "true")
  diff_df <- diff_df %>% mutate(prob = final_df[final_df$etype!="true",1] - final_df[final_df$etype=="true",1])
  
  p3 <- TranPlot(diff_df,"Sleep",diff = T)
  p4 <- TranPlot(diff_df,"Wake",diff = T)
  
  return(list(p1,p2,p3,p4))
}



BoxplotClust <- function(list_ind,inc_out = T){
  final_df <- data.frame()
  num_of_sims <- length(SingleSim)
  
  if (list_ind == 3){
    ylabel <- "Cluster Mean"
    xlabel <- ""
    title <- "Cluster Mean and Mixing Proportion by Number of Support Points"
  }
  if (list_ind == 5){
    ylabel <- "Mixing Proportion"
    xlabel <- "Cluster Index"
    title <- ""
    }
  
  for (sim_ind in 1:num_of_sims){
      nRE <- SingleSim[[sim_ind]][[8]]
      
      if (length(dim(SingleSim[[sim_ind]][[list_ind]][[2]])) == 4){
        working_ms <- SingleSim[[sim_ind]][[list_ind]][[2]][1,1,,]
      } else {
        working_ms <- SingleSim[[sim_ind]][[list_ind]][[2]]
      }
        
    
      
      if (!is.null(dim(working_ms)[1])){
        for (clust_ind in 1:dim(working_ms)[1]){
          working_df <- data.frame(estimates = working_ms[clust_ind,],
                                   numberRE = nRE,
                                   clust_ind = clust_ind)
          
          final_df <- rbind(final_df,working_df)
        }
        
      } else {
        working_df <- data.frame(estimates = SingleSim[[sim_ind]][[list_ind]][[2]][1,1,1,],
                                 numberRE = nRE,
                                 clust_ind = 1)
        
        final_df <- rbind(final_df,working_df)
    }
  }
    
  final_df$numberRE <- factor(final_df$numberRE,levels = c(sort(unique(final_df$numberRE))))
  final_df$clust_ind <- factor(final_df$clust_ind,levels = c(sort(unique(final_df$clust_ind))))
  
  
  p <- ggplot(final_df, aes(x=clust_ind, y=estimates)) +
    facet_grid(cols = vars(numberRE)) + 
    labs(x = xlabel, y = ylabel,  title = title) +
    geom_boxplot()
  
  if(!inc_out){p <- p +coord_cartesian(ylim = quantile(final_df$estimates, c(0.025, 0.975)))}
  
  return(p)

}

DecodeBoxplot <- function(SingleSim,title){

  num_of_sims <- length(SingleSim)
  final_df <- data.frame()
  
  for (sim_ind in 1:num_of_sims){
    nRE <- SingleSim[[sim_ind]][[8]]
    
    working_df <- data.frame(estimates = as.vector(SingleSim[[sim_ind]][[9]]),
                             accType = rep(c("Both","Wake","Sleep"),dim(SingleSim[[sim_ind]][[9]])[2]),
                             numberRE = nRE)
    final_df <- rbind(final_df,working_df)
  }
  
  final_df$numberRE <- factor(final_df$numberRE,levels = c(sort(unique(final_df$numberRE))))
  
  
    
  
  
  ggplot(final_df, aes(x=accType, y=estimates, color = accType)) +
    geom_boxplot()+
    facet_grid(cols = vars(numberRE)) +
    labs(x = "Activity Type", y = "Percent Correcly Predicted")+ 
    guides(color="none") + 
    ggtitle(title)
}


SimScatter <- function(SingleSim){

  num_of_sims <- length(SingleSim)
  final_df <- data.frame()
  
  for (sim_ind in 2:num_of_sims){
    
    est <- SingleSim[[sim_ind]][[3]][[2]]
    nRE <- SingleSim[[sim_ind]][[8]]
    
    est2 <- apply(SingleSim[[sim_ind]][[5]][[2]],1,median)
    
    act_med <- c()
    pi_med <- c()
    for (i in 1:nRE){
      act_med <- c(act_med,median(est[1,1,i,]))
      pi_med <- c(pi_med, est2[i])
    }
      
    
    working_df <- data.frame(act = act_med,
                             mix = pi_med,
                             numberRE = nRE)
    
    final_df <- rbind(final_df,working_df)
  }
  
  final_df$numberRE <- factor(final_df$numberRE,levels = c(sort(unique(final_df$numberRE))))
  
  
  nre.labs <- c(paste(c(1:8), "Support Points"))
  nre.labs[1] <- "1 Support Point"
  names(nre.labs) <- c(1:8)
  
  ggplot(final_df, aes(y=mix, x=act)) +
    geom_point(size =1) + 
    facet_wrap(vars(numberRE),
               labeller = labeller(numberRE = nre.labs),
               nrow = 2) +
    xlab("Wake Activity Cluster") + 
    ylab("Mixing Proportion") + 
    ggtitle("MHMM Mixing Proportion by Wake Activity Clusters") +
    theme_bw()
}
    
  
```


```{r,fig.width=10, fig.height = 7.5, echo =FALSE}

tran_plots <- PlotTran(SingleSim)
tran_plots[[1]]
tran_plots[[3]]

tran_plots[[2]]
tran_plots[[4]]


# grid.arrange(BoxplotClust(3,F),
#              BoxplotClust(5),nrow=2)




g <- arrangeGrob(SimBoxplot(SingleSim,1,2,2,T,expression(Sleep~Initial~Probability~(p[1]))),
             SimBoxplot(SingleSim,3,2,1,T,expression(Wake~Activity~SE~(sigma[0])),2),
             SimBoxplot(SingleSim,3,2,2,T,expression(Sleep~Activity~Mean~(mu[1])),1),
             SimBoxplot(SingleSim,3,2,2,T,expression(Sleep~Activity~SE~(sigma[1])),2),
             SimBoxplot(SingleSim,4,2,1,T,expression(Wake~Zero~Inflated~Probability~(lambda[0]))),
             SimBoxplot(SingleSim,4,2,2,T,expression(Sleep~Zero~Inflated~Probability~(lambda[1]))),
             ncol= 3)

setwd("../Plots")
ggsave("MiscParamBox.png",width = 11,height = 6,g)



SimScatter(SingleSim)
setwd("../Plots")
ggsave("clustmeanmix.png",width = 7,height = 5)


SimBoxplot(SingleSim,3,2,1,T,"Wake Activity SE",2)

# SimBoxplot(SingleSim,6,2,0,F,"Likelihood Step Decreases")

```

```{r}
SimBoxplot(SingleSim,3,2,1,T,"Wake Activity SE",2) + 
  labs(y="Standard Error",
       x="Model",
       title = "Wake Activity SE by Model")  + 
  scale_x_discrete(breaks=c(c(0:8),"Truth"),
        labels=c("Ind HMM",
                 "Shared HMM","MHMM2","MHMM3",
                 "MHMM4","MHMM5","MHMM6",
                 "MHMM7","MHMM8","Truth")) +
  theme(axis.text.x = element_text(angle=45, vjust = 1, hjust=1))

setwd("../Plots")
ggsave("wakeactSE.png",width = 4,height = 4)
```



```{r}
# KL <- function(param1,param2){
#   mu1 <- param1[1]
#   sig1 <- param1[2]
#   mu2 <- param2[1]
#   sig2 <- param2[2]
#   
#   return(log(sig2/sig1)+(sig1^2 + (mu1-mu2)^2)/(2*sig2^2) - 1/2)
# }
# 
# KL(c(0,2),c(6,3))
# 
# 
# KL(c(0,2),c(2,3))
# 
# # Error in serverSocket(port = port) : 
# #   creation of server socket failed: port 11475 cannot be opened
# # Calls: makeCluster -> makePSOCKcluster -> serverSocket
# # Execution halted
# 
# # x <- seq(0,2*pi,.1)
# # b1 <- seq(-1,-.8,.1)
# # b2 <- seq(.8,1,.1)
# # b3 <- seq(-.6,-.4,.1)
# # b4 <- seq(.4,.6,.1)
# # 
# #   for(i1 in 1:length(b1)){
# #     for(i2 in 1:length(b2)){
# #       for(i3 in 1:length(b1)){
# #         for(i4 in 1:length(b2)){
# #           plot(b1[i1]*cos(x) + b2[i2]*sin(x)+b3[i3]*cos(2*x) + b4[i4]*sin(2*x),type = "l",
# #                main = paste(b1[i1],b2[i2],b3[i3],b4[i4]))
# #         }
# #       }
# #   }
# #   }
# 
# b1 <- -.8
# b2 <- 1
# b3 <- -.5
# b4 <- .4
# 
# plot(b1*cos(x) + b2*sin(x)+b3*cos(2*x) + b4*sin(2*x),type = "l")

```

